export const UPDATE_GRID_ROW = "UPDATE_GRID_ROW";
export const APPLY_FILTERS = "APPLY_FILTERS";
export const APPLY_TREE_FILTERS = "APPLY_TREE_FILTERS";
// export const UPDATED_SELECTED_MENU = "UPDATED_SELECTED_MENU";
export const APPLY_GRAPH_FILTERS = "APPLY_GRAPH_FILTERS";
export const REMOVE_FILTERS = "REMOVE_FILTERS";
export const REMOVE_TREE_FILTERS = "REMOVE_TREE_FILTERS";
export const REMOVE_GRAPH_FILTERS = "REMOVE_GRAPH_FILTERS";
export const UPDATED_SELECTED_TAB = "UPDATED_SELECTED_TAB";
export const LOG_OUT_USER = "LOG_OUT_USER";
export const SHOW_ERROR_DIALOG = "SHOW_ERROR_DIALOG";
export const CLOSE_ERROR_DIALOG = "CLOSE_ERROR_DIALOG";
export const SET_TEMPLATES = "SET_TEMPLATES";
export const UPDATE_VERSION = "UPDATE_VERSION";
export const UPDATE_MENUS = "UPDATE_MENUS";
export const SHOW_HIDDEN = "SHOW_HIDDEN";
export const CASE_DATA_SOURCES = [
  "iTechWebSimCaseFile",
  "iTechWebSimCaseFileUser",
  "iTechWebCaseTask",
];
export const UPDATED_SELECTED_CASE = "UPDATE_CASE";
export const UPDATE_DATASOURCES = "UPDATE_DATASOURCES";
export const UPDATE_FOLDERS = "UPDATE_FOLDERS";
export const REMOVE_TAB_FILTERS = "REMOVE_TAB_FILTERS";
