
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class RowData {
    
    public rowData: List[];
    public dateColumn: ColGroupDef[];
}
export class List {
    
    public globalID: number | null;
    public dateCreated: string;
    public globalName: string;
    public fileTypeCount: number | null;
    public fileTypeDescription: string;
    public hour: number;
}
export class ColGroupDef {
    
    public headerName: string;
    public children: Children[];
}
export class Children {
    
    public field: string;
    public width: number | null;
    public minWidth: number | null;
    public maxWidth: number | null;
    public rowGroupIndex: number | null;
    public enableValue: boolean;
    public suppressMenu: boolean;
    public hide: boolean;
    public suppressMovable: boolean;
    public enableRowGroup: boolean;
    public suppressSizeToFit: boolean;
    public filter: string;
    public aggFunc: string;
    public valueFormatter: string;
    public cellClassRules: Colour;
}
export class Colour {
    
    public red: string;
    public amber: string;
    public green: string;
    public bold: string;
}


































