
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
import { ITechDataWebTemplate } from "./ITechDataWebTemplate";




export class ApplyTemplateRequest {
    
    public template: ITechDataWebTemplate;
    public selectedMenuItemId: number | null;
    public selectedTabId: number | null;
}


































