
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
import { ITechDataSecurityObject } from "./ITechDataSecurityObject";
import { CaseUser } from "./CaseUser";
import { ITechDataCase } from "./ITechDataCase";

import { ITechDataUser } from "./ITechDataUser";
import { ITechDataCaseSecurityObject } from "./ITechDataCaseSecurityObject";
import { IRowId } from "./IRowId";





export class CaseModel extends ITechDataCase {
    
    public investigatorITechDataSecurityObject: ITechDataSecurityObject;
    public caseUsers: CaseUser[];
}


































