
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { iTechDataTaskStatusEnum } from "./iTechDataTaskStatusEnum";



export class CaseTask {
    
    public id: string;
    public parent: string;
    public start: number | null;
    public end: number | null;
    public name: string;
    public completed: number | null;
    public dependency: string;
    public durationMinScheduled: number | null;
    public status: iTechDataTaskStatusEnum;
    public isAutomated: boolean;
    public ownerName: string;
}


































