
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { NoteLinkType } from "./NoteLinkType";






export class CaseNotes {
    
    public type: string;
    public noteLinkType: NoteLinkType;
    public notes: CaseNote[];
}
export class CaseNote {
    
    public rowId: number;
    public name: string;
    public detail1: string;
    public detail2: string;
    public type: string;
    public fileDate: string;
}


































