
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { iTechDataFilterEnum } from "./iTechDataFilterEnum";



export class DocumentTerm {
    
    public termId: number;
    public term: string;
    public matchType: iTechDataFilterEnum;
    public unredacted: boolean;
    public count: number;
    public color: string;
}


































