
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { iTechControlColumnEnum } from "./iTechControlColumnEnum";
import { IColumnName } from "./IColumnName";



export class Filter implements IColumnName {
    
    public rowId: number | null;
    public name: string;
    public operation: string;
    public value: any;
    public iTechControlColumnTypeRowId: number | null;
    public isLogin: boolean | null;
    public filters: Filter[];
    public iTechControlColumnType: iTechControlColumnEnum | null;
}


































