
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class FrontendTreeFilter {
    
    public key: string;
    public value: TreeValue[];
}
export class TreeValue {
    
    public rule: string;
    public filters: TreeFilter[];
}
export class TreeFilter {
    
    public rowId: number;
    public name: string;
    public operation: string;
    public value: string;
    public iTechControlColumnTypeRowId: any;
    public iTechControlColumnType: any;
}


































