
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class FrontendFilter {
    
    public key: string;
    public value: Value[];
}
export class Value {
    
    public rule: string;
    public filters: Filter[];
}
export class Filter {
    
    public id: number;
    public rowId: number;
    public name: string;
    public iTechControlColumnTypeRowId: number;
    public columnName: string;
    public operation: string;
    public value: string;
    public operationName: string;
    public valueName: string;
}


































