
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
import { CaseModel } from "./CaseModel";




import { TableFilter } from "./TableFilter";



import { Expression } from "./Expression";



export class ICaseData {
    
    public techDataCase: CaseModel;
    public files: ICaseFilter;
}
export class ICaseFilter {
    
    public rowIds: number[];
    public allChecked: boolean;
    public iTechControlTableRowId: number;
    public filter: TableFilter;
}
export class IAddToCase {
    
    public caseId: number;
    public iTechControlTableRowId: number;
    public expressions: Expression[];
}


































