
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export interface IExportableSim {
    id: string,
    dateTicks: number | null,
    fileTypeRowId: number | null,
    blob: number[],
    fileSize: number | null,
    relativePath: string,
    rowId: number,
    name: string,
    fromAddress: string,
    toAddress: string,
    summary: string,
    isInbound: boolean | null,
    documentGuid: number[]
}
































