
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export interface IFileType {
    fileTypeAbb: string,
    fileTypeDescription: string,
    obDateCreatedString: string,
    iTechControlFileTypeRowId: number,
    obDateCreated: number | null,
    ownerName: string,
    dateYear: number | null,
    dateMonth: number | null
}
































