
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataSecurityObject } from "./ITechDataSecurityObject";



export class IReportConfiguration {
    
    public iTechDataWebTabRowId: number;
    public recipients: ITechDataSecurityObject[];
    public json: string;
    public schedule: string;
    public gid: number;
}


































