
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataSecurityObject } from "./ITechDataSecurityObject";
import { iTechDataTaskStatusEnum } from "./iTechDataTaskStatusEnum";



import { TableFilter } from "./TableFilter";



export class ITaskData {
    
    public taskFilter: ITaskFilter;
    public owner: ITechDataSecurityObject;
    public status: iTechDataTaskStatusEnum;
}
export class ITaskFilter {
    
    public rowIds: number[];
    public allChecked: boolean;
    public filter: TableFilter;
}


































