
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechControlColumnMap } from "./ITechControlColumnMap";
import { ITechControlMap } from "./ITechControlMap";



export class ITechControlTableMap {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public guid: number[];
    public signature: number[];
    public iTechControlTableVirtualRowId: number | null;
    public iTechControlTableRealRowId: number | null;
    public iTechControlMapRowId: number | null;
    public iTechControlColumnMaps: ITechControlColumnMap[];
    public iTechControlMapRow: ITechControlMap;
}


































