
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechControlStoragePolicyVersion } from "./ITechControlStoragePolicyVersion";



export class ITechControlStoragePolicy {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public iTechControlStoragePolicyVersionCurrentRowId: number | null;
    public description: string;
    public abb: string;
    public guid: number[];
    public signature: number[];
    public iTechControlStoragePolicyVersionCurrentRow: ITechControlStoragePolicyVersion;
    public iTechControlStoragePolicyVersions: ITechControlStoragePolicyVersion[];
}


































