
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechResultRow } from "../Extended/ITechResultRow";



export class ITechWebResultSet {
    
    public rowId: number;
    public name: string;
    public securityRowId: number;
    public iTechControlTableRowId: number;
    public savedResultSetRowId: number | null;
    public results: ITechResultRow[];
}


































