
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
import { ITechDataWebTemplate } from "./ITechDataWebTemplate";
import { ITechDataWebTab } from "./ITechDataWebTab";




export class ITechDataWebFilter {
    
    public iTechDataWebTemplate: ITechDataWebTemplate;
    public iTechDataWebTab: ITechDataWebTab;
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public guid: number[];
    public signature: number[];
    public json: string;
    public iTechDataWebFilterTypeRowId: number | null;
    public iTechDataWebTabRowId: number | null;
    public name: string;
    public iTechDataWebTemplateRowId: number | null;
    public iTechDataRuleRowId: number | null;
    public filterCount: number | null;
    public iTechDataSurveillanceRowId: number | null;
}


































