
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataWebComponent } from "./ITechDataWebComponent";
import { ITechDataWebMenu } from "./ITechDataWebMenu";
import { ITechDataWebFilter } from "./ITechDataWebFilter";



export class ITechDataWebTab {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public guid: number[];
    public signature: number[];
    public iTechDataWebMenuRowId: number | null;
    public name: string;
    public position: number | null;
    public selected: boolean | null;
    public iTechDataWebTabParentRowId: number | null;
    public depth: number | null;
    public fixed: boolean | null;
    public iTechDataCaseRowId: number | null;
    public iTechDataWebFolderRowId: number | null;
    public iTechDataWebTabTypeRowId: number | null;
    public iTechDataWebComponents: ITechDataWebComponent[];
    public iTechDataWebMenuRow: ITechDataWebMenu;
    public iTechDataWebTabChild: ITechDataWebTab[];
    public iTechDataWebFilters: ITechDataWebFilter[];
    public iTechDataWebTabParent: ITechDataWebTab;
}


































