
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




import { ITechControlColumn } from "./ITechControlColumn";



import { ITechControlTable } from "./ITechControlTable";



export class ITechDataWebFrontendComponent {
    
    public icon: string;
    public name: string;
    public description: string;
    public rowId: number;
    public id: string;
    public subItems: SubItem[];
    public configureColumns: ConfigureColumn[];
    public componentType: string;
    public paging: Paging;
    public sortBy: string;
    public sortDirection: string;
    public searchText: string;
}
export class Paging {
    
    public start: number;
    public end: number;
}
export class ConfigureColumn {
    
    public icon: string;
    public name: string;
    public description: string;
    public rowId: number;
    public iTechControlColumns: ITechControlColumn[];
    public id: string;
    public subItems: SubItem[];
}
export class SubItem {
    
    public index: number;
    public name: string;
    public width: number;
    public minWidth: number;
    public id: string;
    public advancedFilterSelected: boolean | null;
    public dateArchived: any;
    public dateInserted: number | null;
    public dateModified: any;
    public description: string;
    public gridIndex: number | null;
    public gridSelected: boolean | null;
    public guid: any;
    public helperText: string;
    public iTechControlColumnTypeRowId: number | null;
    public iTechControlTableRowId: number | null;
    public notes: any;
    public rowId: number | null;
    public signature: any;
    public status: any;
    public treeIndex: number | null;
    public treeSelected: boolean | null;
    public iTechControlTable: ITechControlTable;
    public checked: boolean | null;
    public types: any;
}


































