
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataTaskOutcomeType } from "./ITechDataTaskOutcomeType";
import { ITechDataTaskStatusType } from "./ITechDataTaskStatusType";
import { ITechDataTaskType } from "./ITechDataTaskType";
import { ITechDataTaskTypeToOutcome } from "./ITechDataTaskTypeToOutcome";



export class ITechDataTask {
    
    public rowId: number;
    public isTemplate: boolean | null;
    public iTechDataTaskRootRowId: number | null;
    public iTechDataTaskParentRowId: number | null;
    public iTechDataTaskPredessorRowId: number | null;
    public iTechDataTaskTypeRowId: number | null;
    public iTechDataTaskStatusTypeRowId: number | null;
    public iTechDataTaskOutcomeTypeRowId: number | null;
    public taskName: string;
    public taskDetails: string;
    public percentageComplete: number | null;
    public dateStartScheduled: number | null;
    public durationMinScheduled: number | null;
    public dateStartActual: number | null;
    public durationMinActual: number | null;
    public hasPredessor: boolean | null;
    public predessorRowId: number | null;
    public args: string;
    public iTechControlTableReferenceTypeRowId: number | null;
    public riskRatingManual: number | null;
    public riskRatingMl01: number | null;
    public riskRatingMl02: number | null;
    public priorityManual: number | null;
    public status: number[];
    public guid: number[];
    public signature: number[];
    public outcomeNotes: string;
    public hierarchyString: string;
    public hierarchy: any;
    public dateArchived: number | null;
    public iTechDataTaskMethodTypeRowId: number | null;
    public iTechDataWorkflowRowId: number | null;
    public iTechDataTaskOutcomeTypeRow: ITechDataTaskOutcomeType;
    public iTechDataTaskStatusTypeRow: ITechDataTaskStatusType;
    public iTechDataTaskTypeRow: ITechDataTaskType;
    public iTechDataTaskTypeToOutcomes: ITechDataTaskTypeToOutcome[];
}


































