
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlOperatorEnum {
    equals = 0,
    notEquals = 1,
    lessThan = 2,
    greaterThan = 3,
    contains = 4,
    startsWith = 5,
    in = 6,
    like = 7
}

































