
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlTrackingEnum {
    c4 = 1,
    vmigStandard = 2,
    hyperengineCDR = 3,
    tru = 4,
    iTechArchive = 5,
    iTechIndex = 6,
    hyperengineSip = 7,
    vmigTru = 8,
    hyperengineTru = 9,
    camelTru = 10,
    datTru = 11,
    cerillionTru = 12
}

































