
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class ITechDataDpiaV2 {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public guid: number[];
    public signature: number[];
    public controllerName: string;
    public dpoSubject: string;
    public controllerContactName: string;
    public needForDpia: string;
    public processingNature: string;
    public processingScope: string;
    public processingContext: string;
    public processingPurpose: string;
    public stakeholderConsultation: string;
    public complianceMeasures: string;
    public riskSource: string;
    public riskHarmLikelihood: number | null;
    public riskHarmSeverity: number | null;
    public riskOverall: number | null;
    public riskToReduce: string;
    public riskReduction: string;
    public riskReductionEffect: number | null;
    public riskResidual: number | null;
    public riskMeasureApproved: boolean | null;
    public measuresApprovedByName: string;
    public measureApprovedByPosition: string;
    public measureApprovedByDate: number | null;
    public residualRiskApprovedByName: string;
    public residualRiskApprovedByPosition: string;
    public residualRiskApprovedByDate: number | null;
    public dpoadviceProvidedByName: string;
    public dpoadviceProvidedByPosition: string;
    public dpoadviceProvidedByDate: number | null;
    public dpoadviceSummary: string;
    public dpoadviceAcceptedByName: string;
    public dpoadviceAcceptedByPosition: string;
    public dpoadviceAcceptedByDate: number | null;
    public dpoadviceAcceptedComments: string;
    public responsesReviewedByName: string;
    public responsesReviewedByPosition: string;
    public responsesReviewedByDate: number | null;
    public responsesReviewedComments: string;
    public dpiakeptByName: string;
    public dpiakeptByPosition: string;
    public dpiakeptByDate: number | null;
}


































