
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechControlDatabase } from "./ITechControlDatabase";
import { ITechControlLicenseCode } from "./ITechControlLicenseCode";
import { ITechControlRegion } from "./ITechControlRegion";



export class ITechControlGlobal {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public dateActivated: number | null;
    public status: number[];
    public name: string;
    public validUrls: string;
    public guid: number[];
    public signature: number[];
    public iTechControlGlobalParentRowId: number | null;
    public haveMultipleSources: number | null;
    public iTechControlTreeStructureTypeRowId: number | null;
    public skin: string;
    public truCustomerId: number | null;
    public timeoutTicks: number | null;
    public poc: boolean | null;
    public hasPrivateWebsite: boolean | null;
    public globalLegalHold: boolean | null;
    public connectionString: string;
    public abbreviation: string;
    public iTechControlRetentionPolicyRowId: number | null;
    public iTechControlContractRowId: number | null;
    public isChargeable: boolean | null;
    public seedKey1: string;
    public seedKey2: string;
    public args: string;
    public saml: boolean | null;
    public dualAuthenticationEmail: boolean | null;
    public dualAuthenticationSms: boolean | null;
    public dateLegalHoldStart: number | null;
    public dateLegalHoldEnd: number | null;
    public haltProcess: boolean | null;
    public authJson: string;
    public isSimCte: boolean | null;
    public iTechControlDatabases: ITechControlDatabase[];
    public iTechControlLicenseCodes: ITechControlLicenseCode[];
    public iTechControlRegions: ITechControlRegion[];
}


































