
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataCompany } from "./ITechDataCompany";
import { ITechDataSecurityObjectSourceType } from "./ITechDataSecurityObjectSourceType";
import { ITechDataSecurityObjectType } from "./ITechDataSecurityObjectType";
import { ITechDataUserIdentifier } from "./ITechDataUserIdentifier";
import { ITechDataUserToRole } from "./ITechDataUserToRole";
import { ITechDataSecurityObject } from "./ITechDataSecurityObject";
import { ITechDataMembership } from "./ITechDataMembership";
import { ITechDataUserIdentifierToCollectionType } from "./ITechDataUserIdentifierToCollectionType";
import { ITechDataSecurityObjectToRetentionPolicy } from "./ITechDataSecurityObjectToRetentionPolicy";



export class ITechDataUser {
    
    public rowId: number;
    public datePasswordChanged: number | null;
    public forename: string;
    public surname: string;
    public title: string;
    public onLegalHold: boolean | null;
    public username: string;
    public displayName: string;
    public truSubscriberId: number | null;
    public truQuoteReference: string;
    public truBlackberry: boolean | null;
    public isTemplate: boolean | null;
    public isChargeable: boolean | null;
    public dateReconciled: number | null;
    public timezone: string;
    public dateExpired: number | null;
    public isCollection: boolean | null;
    public defaultObjectAuthorisationRulesBinary: number[];
    public iTechControlGlobalRowId: number | null;
    public iTechControlRegionRowId: number | null;
    public iTechControlRetentionPolicyRowId: number | null;
    public iTechControlContractRowId: number | null;
    public iTechDataSecurityObjectGlobalRowId: number | null;
    public iTechDataSecurityObjectSourceTypeRowId: number | null;
    public iTechDataSecurityObjectTypeRowId: number | null;
    public iTechDataSecurityObjectParentRowId: number | null;
    public iTechSimFolderGuid: number[];
    public status: number[];
    public guid: number[];
    public signature: number[];
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public dateActivated: number | null;
    public iTechDataCompanyRowId: number | null;
    public externalReference: string;
    public iTechDataCurrentUserToRoleRowId: number | null;
    public iTechDataCompanyRow: ITechDataCompany;
    public iTechDataSecurityObjectSourceTypeRow: ITechDataSecurityObjectSourceType;
    public iTechDataSecurityObjectTypeRow: ITechDataSecurityObjectType;
    public iTechDataUserIdentifiers: ITechDataUserIdentifier[];
    public iTechDataUserToRoles: ITechDataUserToRole[];
    public iTechDataSecurityObject: ITechDataSecurityObject;
    public iTechDataMembershipRows: ITechDataMembership[];
    public iTechDataUserIdentifierToCollectionTypeRows: ITechDataUserIdentifierToCollectionType[];
    public iTechDataSecurityObjectToRetentionPolicyRows: ITechDataSecurityObjectToRetentionPolicy[];
}


































