
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechDataUserIdentifierEnum {
    email = 1,
    telNo = 2,
    ddiIn = 3,
    ddiOut = 4,
    fixedVoice = 5,
    mobVoice = 6,
    perEmail = 7,
    perMobile = 8,
    traderId = 9,
    name = 10,
    messenger = 11,
    door = 12,
    ipAddress = 13,
    ipAndPort = 14
}

































