
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebCollectionTotal implements IRowId {
    
    public rowId: number;
    public gid: number;
    public iTechMasterDateRowId: number | null;
    public iTechControlGlobalRowId: number | null;
    public iTechControlFileTypeRowId: number | null;
    public fileTypeCount: number | null;
    public dateCreated: Date | null;
    public dateYear: number | null;
    public dateQtr: number | null;
    public dateDayOfWeek: number | null;
    public dateMonth: number | null;
    public dateWeekOfYear: number | null;
    public dateDay: number | null;
    public dateHour: number | null;
    public monthId: number | null;
    public dayId: number | null;
    public dateCreatedUtc: number | null;
    public globalName: string;
    public fileTypeAbb: string;
    public fileTypeDescription: string;
}


































