
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataCaseStatusType } from "./ITechDataCaseStatusType";
import { ITechDataCaseSubType } from "./ITechDataCaseSubType";



export class ITechDataCaseStatusToSubTypeLookup {
    
    public rowId: number;
    public iTechDataCaseSubTypeRowId: number;
    public iTechDataCaseStatusTypeRowId: number | null;
    public iTechDataCaseStatusTypePreviousRowId: number | null;
    public sortOrder: number | null;
    public isStatusReversible: boolean | null;
    public iTechDataCaseStatusTypeRow: ITechDataCaseStatusType;
    public iTechDataCaseSubTypeRow: ITechDataCaseSubType;
}


































