
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebManageEntity implements IRowId {
    
    public rowId: number;
    public gid: number;
    public objectId: string;
    public value: string;
    public iTechDataManageEntityTypeRowId: number | null;
    public entityTypeAbb: string;
    public abbPrint: string;
    public entityTypeDescription: string;
    public iTechDataManageObjectTypeRowId: number | null;
    public objectTypeAbb: string;
    public objectTypeDescription: string;
    public iTechDataManageResetTypeRowId: number | null;
    public resetTypeAbb: string;
    public resetTypeDescription: string;
    public status: string;
    public queuePreCollection: string;
    public queueToBeProcessed: string;
    public queueToBeIndexed: string;
    public processedInTimeSlice: string;
    public dateInserted: number | null;
    public dateInsertedString: string;
    public dateModified: number | null;
    public dateModifiedString: string;
    public dateObjectUpdatedUtc: number | null;
    public dateObjectUpdatedUtcString: string;
    public dateOfRefreshUtc: number | null;
    public dateOfRefreshUtcString: string;
    public dateAlarmUtc: number | null;
    public dateAlarmUtcString: string;
    public timeToProcessSeconds: number | null;
    public refreshIntervalSeconds: number | null;
    public alarmIncrementSeconds: number | null;
    public stTimeExclusion: number | null;
    public description: string;
    public documentation: string;
    public documentationUrl: string;
    public args: string;
    public dateTriggeredUtc: number | null;
    public dateTriggeredUtcString: string;
    public isMonitoredEditable: boolean | null;
}


































