
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebUserGroup implements IRowId {
    
    public rowId: number;
    public displayName: string;
    public dateInserted: number | null;
    public dateArchived: number | null;
    public dateInsertedString: string;
    public dateArchivedString: string;
    public groups: string;
    public groupIds: string;
    public gid: number;
}


































