
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebHr implements IRowId {
    
    public iTechDataUserRowId: number;
    public gid: number;
    public iTechDataHrRecordRowId: number | null;
    public userName: string;
    public employmentStartDate: number | null;
    public employmentStartDateString: string;
    public employmentEndDate: number | null;
    public employmentEndDateString: string;
    public iTechDataUserHrReasonForLeavingTypeRowId: number | null;
    public userHrReasonForLeavingType: string;
    public userHrReasonForLeavingTypeDescription: string;
    public iTechDataUserHrGenderIdentityTypeRowId: number | null;
    public userHrGenderIdentityType: string;
    public userHrGenderIdentityTypeDescription: string;
    public iTechDataUserHrMaritalStatusTypeRowId: number | null;
    public userHrMaritalStatusType: string;
    public userHrMaritalStatusTypeDescription: string;
    public photoImageDocumentGuid: number[];
    public propertyNameNo: string;
    public streetName1: string;
    public streetName2: string;
    public town: string;
    public city: string;
    public country: string;
    public postCode: string;
    public iTechDataHrDisciplinaryRowId: number | null;
    public disciplinaryStartDate: number | null;
    public disciplinaryStartDateString: string;
    public disciplinaryEndDate: number | null;
    public disciplinaryEndDateString: string;
    public iTechDataHrDisciplinaryTypeRowId: number | null;
    public disciplinaryType: string;
    public disciplinaryTypeDescription: string;
    public riskRating: number | null;
    public roleStartDate: number | null;
    public roleStartDateString: string;
    public roleEndDate: number | null;
    public roleEndDateString: string;
    public iTechDataRoleRowId: number | null;
    public roleName: string;
    public iTechDataRoleTypeRowId: number | null;
    public roleType: string;
    public iTechDataRoleLocationRowId: number | null;
    public roleLocation: string;
    public roleLocationIds: string;
    public roleLocations: string;
    public iTechDataRoleLocationTypeRowId: number | null;
    public roleLocationType: string;
    public socialMediaUrlArg00: string;
    public socialMediaUrlArg01: string;
    public socialMediaUrlArg02: string;
    public iTechDataSocialMediaTypeRowId: number | null;
    public socialMediaType: string;
    public socialMediaTypeDescription: string;
    public rowId: number;
    public level: number;
}


































