
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechDataAssurePolicyFrequencyEnum {
    minuteInterval = 1,
    hourlyInterval = 2,
    dailyInterval = 3,
    weeklyInterval = 4,
    monthlyInterval = 5
}

































