
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebHolderAction implements IRowId {
    
    public rowId: number;
    public gid: number;
    public dateInserted: number | null;
    public dateInsertedString: Date | null;
    public dateModified: number | null;
    public dateModifiedString: Date | null;
    public actionStatus: number | null;
    public actionStatusSub: number | null;
    public iTechControlServiceTypeRowId: number | null;
    public serviceTypeAbb: string;
    public serviceTypeDescription: string;
    public iTechControlServiceTypeSubRowId: number | null;
    public iTechControlDatabaseRowId: number | null;
    public databaseDetails: string;
    public action: number | null;
    public rangeStart: number | null;
    public rangeEnd: number | null;
    public dateToRun: number | null;
    public dateToRunString: Date | null;
    public iTechHolderActionParentRowId: number | null;
    public iTechControlGlobalRowId: number | null;
    public globalName: string;
    public iTechControlRegionRowId: number | null;
    public details: string;
    public args: string;
    public errMsg: string;
    public comments: string;
    public obStartDate: number | null;
    public obStartDateString: Date | null;
    public obEndDate: number | null;
    public obEndDateString: Date | null;
    public duplicateKey: string;
    public iTechControlProcessGridRowId: number | null;
    public iTechControlServicesToHostsToServiceTypeToDatabaseRowId: number | null;
    public acknowledged: boolean | null;
    public sourceType: string;
    public iTechRegionSecurityObjectRowId: number | null;
}


































