
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechDataActionEnum {
    filterSet = 1,
    email = 2,
    sms = 3,
    retention = 4,
    class = 5,
    snmp = 6,
    tagging = 7,
    storage = 8,
    log = 9,
    notify = 10,
    workflow = 11
}

































