
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechControlFileSubType } from "./ITechControlFileSubType";
import { ITechControlFileTypeToKeyType } from "./ITechControlFileTypeToKeyType";
import { ITechControlStoragePolicyVersionToFileType } from "./ITechControlStoragePolicyVersionToFileType";



export class ITechControlFileType {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public description: string;
    public abb: string;
    public realFileTypeParentRowId: number | null;
    public validated: Date | null;
    public maxSizeMbyte: number | null;
    public allIncExc: number | null;
    public guid: number[];
    public signature: number[];
    public iTechControlFileSubTypes: ITechControlFileSubType[];
    public iTechControlFileTypeToKeyTypes: ITechControlFileTypeToKeyType[];
    public iTechControlStoragePolicyVersionToFileTypes: ITechControlStoragePolicyVersionToFileType[];
}


































