
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechDataManageEntityEnum {
    none = 0,
    soteria_1_ = 1,
    environment_1_x_ = 2,
    dataCentre_1_x_x_ = 3,
    cpU_1_x_x_1001_x_1001_ = 5,
    cpuCore_1_x_x_1001_x_1001_x_ = 6,
    memoryCapacityGb_1_x_x_1001_x_1002_ = 7,
    diskInformation_1_x_x_1001_x_1003_ = 8,
    diskDrive_1_x_x_1001_x_1003_x_ = 9,
    diskCapacityGb_1_x_x_1001_x_1003_x_1001_ = 10,
    diskSpaceUtilisedGb_1_x_x_1001_x_1003_x_1002_ = 11,
    diskSpaceFreeGb_1_x_x_1001_x_1003_x_1003_ = 12,
    diskSpaceFreePercent_1_x_x_1001_x_1003_x_1004_ = 13,
    soteriaHostInstance_1_x_x_1001_x_x_ = 14,
    status_1_x_x_1001_x_x_1_ = 15,
    statusSet_1_x_x_1001_x_x_101_ = 16,
    soteriaService_1_x_x_1001_x_x_1001_ = 17,
    soteriaServiceResetHolder_1_x_x_1001_x_x_1001_1_ = 18,
    soteriaSeriviceResetHolderActionInstance_1_x_x_1001_x_x_1001_1_x_ = 19,
    status_1_x_x_1001_x_x_1001_1_x_1_ = 20,
    startTimeUtc_1_x_x_1001_x_x_1001_1_x_2_ = 21,
    stopTimeUtc_1_x_x_1001_x_x_1001_1_x_3_ = 22,
    statusSet_1_x_x_1001_x_x_1001_1_x_101_ = 23,
    soteriaServiceActionManager_1_x_x_1001_x_x_1001_1_ = 24,
    soteriaServiceActionManagerInstance_1_x_x_1001_x_x_1001_2_x_ = 25,
    status_1_x_x_1001_x_x_1001_2_x_1_ = 26,
    startTimeUtc_1_x_x_1001_x_x_1001_2_x_2_ = 27,
    stopTimeUtc_1_x_x_1001_x_x_1001_2_x_3_ = 28,
    iterationSuccessInTimeSlice_1_x_x_1001_x_x_1001_2_x_4_ = 29,
    iterationFailureInTimeSlice_1_x_x_1001_x_x_1001_2_x_5_ = 30,
    actionManagerQueueDepth1_1_x_x_1001_x_x_1001_2_x_11_ = 31,
    actionManagerQueueDepth2_1_x_x_1001_x_x_1001_2_x_12_ = 32,
    actionManagerQueueDepth3_1_x_x_1001_x_x_1001_2_x_13_ = 33,
    statusSet_1_x_x_1001_x_x_1001_2_x_101_ = 34,
    soteriaServiceIndexer_1_x_x_1001_x_x_1001_3_ = 35,
    soteriaServiceIndexerInstance_1_x_x_1001_x_x_1001_3_x_ = 36,
    status_1_x_x_1001_x_x_1001_3_x_1_ = 37,
    startTimeUtc_1_x_x_1001_x_x_1001_3_x_2_ = 38,
    stopTimeUtc_1_x_x_1001_x_x_1001_3_x_3_ = 39,
    iterationSuccessInTimeSlice_1_x_x_1001_x_x_1001_3_x_4_ = 40,
    iterationFailureInTimeSlice_1_x_x_1001_x_x_1001_3_x_5_ = 41,
    indexerQueueDepth1_1_x_x_1001_x_x_1001_3_x_11_ = 42,
    indexerQueueDepth2_1_x_x_1001_x_x_1001_3_x_12_ = 43,
    indexerQueueDepth3_1_x_x_1001_x_x_1001_3_x_13_ = 44,
    statusSet_1_x_x_1001_x_x_1001_3_x_101_ = 45,
    soteriaCollector_1_x_x_1002_ = 46,
    soteriaCollectorInstance_1_x_x_1002_x_ = 47,
    status_1_x_x_1002_x_1_ = 48,
    startTimeUtc_1_x_x_1002_x_2_ = 49,
    stopTimeUtc_1_x_x_1002_x_3_ = 50,
    iterationSuccessInTimeSlice_1_x_x_1002_x_4_ = 51,
    iterationFailureInTimeSlice_1_x_x_1002_x_5_ = 52,
    collectorQueueDepth1_1_x_x_1002_x_11_ = 53,
    collectorQueueDepth2_1_x_x_1002_x_12_ = 54,
    collectorQueueDepth3_1_x_x_1002_x_13_ = 55,
    statusSet_1_x_x_1002_x_14_ = 56,
    soteriaInLineMonitor_1_x_x_1003_ = 57,
    soteriaInLineMonitorInstance_1_x_x_1003_x_ = 58,
    status_1_x_x_1003_x_1_ = 59,
    startTimeProcessUtc_1_x_x_1003_x_2_ = 60,
    stopTimeProcessUtc_1_x_x_1003_x_3_ = 61,
    soteriaWebService_1_x_x_1004_ = 62,
    soteriaAdmin_1_x_x_1004_ = 63,
    soteriaAdminInstance_1_x_x_1004_x_ = 64,
    soteriaSmtpRelayCheck_1_x_x_1005_ = 65,
    soteriaSmtpRelayCheckInstance_1_x_x_1005_x_ = 66,
    soteriaHolder_1_x_x_1006_ = 67,
    soteriaHolderInstance_1_x_x_1006_x_ = 68,
    iterationSuccessInTimeSlice_1_x_x_1006_x_4_ = 69,
    iterationFailureInTimeSlice_1_x_x_1006_x_5_ = 70,
    soteriaHolderByServiceType_1_x_x_1006_x_1001_ = 71,
    soteriaHolderByServiceTypeInstance_1_x_x_1006_x_1001_x_ = 72,
    iterationSuccessInTimeSlice_1_x_x_1006_x_1001_x_4_ = 73,
    iterationFailureInTimeSlice_1_x_x_1006_x_1001_x_5_ = 74,
    status_1_x_x_1_ = 75,
    statusSet_1_x_x_101_ = 76,
    soteriaRetentionDeletion_1_x_x_1008_ = 77,
    soteriaRetentionDeletionInstance_1_x_x_1008_x_ = 78,
    status_1_x_x_1008_x_1_ = 79,
    startTimeUtc_1_x_x_1008_x_2_ = 80,
    stopTimeUtc_1_x_x_1008_x_3_ = 81,
    iterationSuccessInTimeSlice_1_x_x_1008_x_4_ = 82,
    iterationFailureInTimeSlice_1_x_x_1008_x_5_ = 83,
    soteriaServiceManagement_1_x_x_1001_x_x_1001_4_ = 84,
    soteriaServiceManagementInstance_1_x_x_1001_x_x_1001_4_x_ = 85,
    status_1_x_x_1001_x_x_1001_4_x_1_ = 86,
    startTimeUtc_1_x_x_1001_x_x_1001_4_x_2_ = 87,
    stopTimeUtc_1_x_x_1001_x_x_1001_4_x_3_ = 88,
    replication_1_x_x_1001_x_x_1001_4_x_1001_ = 89,
    replicationInstance_1_x_x_1001_x_x_1001_4_x_1001_x_ = 90,
    replicationV2_1_x_x_1001_x_x_1001_4_x_1002_ = 91,
    replicationInstanceV2_1_x_x_1001_x_x_1001_4_x_1002_x_ = 92,
    eventManagement_1_x_x_1001_x_x_1001_4_x_1003_ = 93,
    eventManagementInstance_1_x_x_1001_x_x_1001_4_x_1003_x_ = 94,
    onSiteEdge_1_x_x_1007_ = 95,
    onSiteEdgeDevice_1_x_x_1007_x_ = 96,
    onSiteEdgeDeviceInstance_1_x_x_1007_x_x_ = 97,
    status_1_x_x_1007_x_1_ = 98,
    startTimeUtc_1_x_x_1007_x_2_ = 99,
    stopTimeUtc_1_x_x_1007_x_3_ = 100,
    iterationSuccessInTimeSlice_1_x_x_1007_x_4_ = 101,
    iterationFailureInTimeSlice_1_x_x_1007_x_5_ = 102,
    cpU_1_x_x_1007_x_1001_ = 103,
    cpuCore_1_x_x_1007_x_1001_x_ = 104,
    memoryCapacityGb_1_x_x_1007_x_1002_ = 105,
    diskInformation_1_x_x_1007_x_1003_ = 106,
    diskDrive_1_x_x_1007_x_1003_x_ = 107,
    diskCapacityGb_1_x_x_1007_x_1003_x_1001_ = 108,
    diskSpaceUtilisedGb_1_x_x_1007_x_1003_x_1002_ = 109,
    diskSpaceFreeGb_1_x_x_1007_x_1003_x_1003_ = 110,
    diskSpaceFreePercent_1_x_x_1007_x_1003_x_1004_ = 111,
    onSiteQueueDepth1_1_x_x_1007_x_11_ = 112,
    onSiteQueueDepth2_1_x_x_1007_x_12_ = 113,
    onSiteQueueDepth3_1_x_x_1007_x_13_ = 114,
    statusSet_1_x_x_1007_x_14_ = 115,
    inProgress_1_x_x_1007_x_15_ = 116,
    soteriaServiceCache_1_x_x_1001_x_x_1001_5_ = 117,
    soteriaServiceCacheInstance_1_x_x_1001_x_x_1001_5_x_ = 118,
    status_1_x_x_1001_x_x_1001_5_x_1_ = 119,
    startTimeUtc_1_x_x_1001_x_x_1001_5_x_2_ = 120,
    iterationSuccessInTimeSlice_1_x_x_1001_x_x_1001_5_x_4_ = 121,
    iterationFailureInTimeSlice_1_x_x_1001_x_x_1001_5_x_5_ = 122,
    statusSet_1_x_x_1001_x_x_1001_5_x_101_ = 123,
    softwareVersionCurrent_1_x_x_1001_x_x_1001_1_x_4_ = 124,
    restartIntervalMinutes_1_x_x_1001_x_x_1001_1_x_5_ = 125,
    softwareVersionSet_1_x_x_1001_x_x_1001_1_x_104_ = 126,
    startTimeUtc_1_x_x_1001_x_x_2_ = 127,
    stopTimeUtc_1_x_x_1001_x_x_3_ = 128
}

































