
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebAlert implements IRowId {
    
    public rowId: number;
    public gid: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public dateInsertedString: string;
    public dateModifiedString: string;
    public dateArchivedString: string;
    public iTechDataSurveillanceRowId: number | null;
    public surveillanceName: string;
    public iTechDataRiskTypeRowId: number | null;
    public riskType: string;
    public iTechDataCaseRowId: number | null;
    public caseName: string;
    public caseReference: string;
    public threshold: number | null;
    public detail: string;
    public score: number | null;
    public iTechDataLexiconGroupRowId: number | null;
    public lexiconGroupName: string;
    public iTechDataOutcomeTypeRowId: number | null;
    public outcomeType: string;
    public iTechLinkedRowId: number | null;
    public iTechControlTableReferenceTypeRowId: number | null;
    public triggers: string;
    public userCount: number | null;
    public iTechDataUserRowId: number | null;
    public userName: string;
}


































