
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class ITechWebAuthenticatedUser {
    
    public id: string;
    public rowId: number;
    public iTechControlGlobalRowId: number | null;
    public forename: string;
    public surname: string;
    public username: string;
    public password: string;
    public dateInserted: number | null;
    public identifier: string;
    public iTechDataUserIdentifierTypeRowId: number | null;
    public pwd: string;
    public dateChallenged: number | null;
    public iTechDataWebTabRowId: number | null;
    public iTechDataWebMenuRowId: number | null;
    public iTechDataSecurityObjectMenuOwnerRowId: number | null;
    public isVendor: boolean | null;
    public iTechDataSecurityObjectTypeRowId: number | null;
    public iTechDataAuthTypeRowId: number | null;
}


































