
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechDataTaskOutcomeEnum {
    successful = 1,
    taskNotRelevant = 2,
    cannotDelete = 3,
    failure = 4,
    init = 5,
    falseAlarm = 6,
    relevant = 7,
    escalated = 8,
    hold = 9,
    refer = 10,
    complete = 11
}

































