
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlPerformanceMetricsEnum {
    holder = 1,
    archive = 2,
    addToSimFold = 3,
    addToSim = 4,
    retentionPolicy = 5,
    classification = 6,
    notification = 7,
    index = 8
}

































