
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataFilterType } from "./ITechDataFilterType";
import { ITechDataTermType } from "./ITechDataTermType";



export class ITechDataTerm {
    
    public rowId: number;
    public iTechDataTermTypeRowId: number | null;
    public iTechDataFilterTypeRowId: number | null;
    public iTechDataWebFilterRowId: number | null;
    public addToAllCases: boolean | null;
    public term: string;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public iTechDataFilterTypeRow: ITechDataFilterType;
    public iTechDataTermTypeRow: ITechDataTermType;
}


































