
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechDataRiskCategoryEnum {
    antiFinancialCrime = 1,
    businessConduct = 2,
    complaints = 3,
    conflictsOfInterest = 4,
    employeeConduct = 5,
    informationBarrier = 6,
    informationSecurity = 7,
    marketConduct = 8,
    materialNonPublicInfo = 9,
    riskInsight = 10,
    salesPractice = 11
}

































