
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITableReference } from "./ITableReference";



export class ITechDataTaskToTableReference implements ITableReference {
    
    public rowId: number;
    public iTechControlTableReferenceTypeRowId: number | null;
    public iTechControlTableReferenceRowId: number | null;
    public iTechLinkedRowId: number | null;
}


































