
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechAudit } from "./ITechAudit";
import { ITechControlDatabase } from "./ITechControlDatabase";
import { ITechControlRegion } from "./ITechControlRegion";
import { ITechControlServicesToHostsToServiceTypeToDatabase } from "./ITechControlServicesToHostsToServiceTypeToDatabase";
import { ITechControlTreeRootPath } from "./ITechControlTreeRootPath";



export class ITechControlHost {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public fqHostName: string;
    public isManaged: boolean | null;
    public iTechControlRegionRowId: number | null;
    public guid: number[];
    public signature: number[];
    public iTechControlProcessGridRowId: number | null;
    public args: string;
    public iTechAudits: ITechAudit[];
    public iTechControlDatabases: ITechControlDatabase[];
    public iTechControlRegionRow: ITechControlRegion;
    public iTechControlServicesToHostsToServiceTypeToDatabases: ITechControlServicesToHostsToServiceTypeToDatabase[];
    public iTechControlTreeRootPaths: ITechControlTreeRootPath[];
}


































