
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebLicensing implements IRowId {
    
    public rowId: number;
    public gid: number;
    public iTechDataLicensingPartNumberRowId: number | null;
    public quantityPurchased: number | null;
    public dateLicensed: number | null;
    public dateLicensedString: string;
    public licenseDurationInMonths: number | null;
    public isAutoRenew: boolean | null;
    public autoRenewOffsetInMonths: number | null;
    public notes: string;
    public purchaseOrderNumber: string;
    public dateInserted: number | null;
    public dateInsertedString: string;
    public dateModified: number | null;
    public dateModifiedString: string;
    public dateArchived: number | null;
    public dateArchivedString: string;
    public partNumberAbb: string;
    public partNumberDescription: string;
    public iTechDataLicensingPartNumberInvoicingCategoryRowId: number | null;
    public invoicingCategoryAbb: string;
    public invoicingCategoryDescription: string;
    public invoicingCategoryNotes: string;
    public iTechDataLicensingPartNumberTypeRowId: number | null;
    public iTechDataLicensingAssociationTypeRowId: number | null;
    public associationTypeAbb: string;
    public associationTypeDescription: string;
    public partNumberTypeAbb: string;
    public partNumberTypeDescription: string;
    public partNumberNotes: string;
    public stdAutoReNewOffsetInMonths: number | null;
    public stdIsAutoRenew: boolean | null;
    public stdLicenseDurationInMonths: number | null;
    public collectionIsAutoRenew: boolean | null;
    public collectionLicenseDurationInMonths: number | null;
    public collectionDateInserted: number | null;
    public collectionDateInsertedString: string;
    public collectionDateLicensed: number | null;
    public collectionDateLicensedString: string;
    public iTechControlCollectionTypeRowId: number | null;
    public collectionTypeAbb: string;
    public collectionTypeDescription: string;
    public iTechDataUserIdentifierRowId: number | null;
    public identifier: string;
    public iTechDataUserRowId: number | null;
    public iTechDataUserIdentifierTypeRowId: number | null;
    public identifierTypeAbb: string;
    public identifierTypeDescription: string;
    public userFullName: string;
    public username: string;
    public users: string;
    public identifiers: string;
    public userCount: number | null;
    public identifierCount: number | null;
    public expiryDate: Date | null;
    public isExpired: boolean | null;
}


































