
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class ITechDataSurveillance {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public guid: number[];
    public signature: number[];
    public iTechDataSecurityObjectRowId: number | null;
    public name: string;
    public threshold: number | null;
    public isOrdered: boolean | null;
    public timespan: number | null;
    public description: string;
    public comments: string;
    public iTechDataRiskTypeRowId: number | null;
    public iTechDataRiskCategoryTypeRowId: number | null;
    public iTechDataScenarioTypeRowId: number | null;
    public disabled: boolean | null;
}


































