
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlTranscriptionEngineEnum {
    none = 0,
    bertinVer2_0 = 1,
    speechmaticsVer1_0 = 2,
    microsoftContainerVer3_7 = 3,
    intelligentVoiceVer2_0 = 4
}

































