
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechControlDatabase } from "./ITechControlDatabase";
import { ITechControlExpression } from "./ITechControlExpression";
import { ITechControlTableMap } from "./ITechControlTableMap";



export class ITechControlMap {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public guid: number[];
    public signature: number[];
    public iTechControlDatabaseVirtualRowId: number | null;
    public iTechControlDatabaseRealRowId: number | null;
    public iTechControlDatabaseRealRow: ITechControlDatabase;
    public iTechControlDatabaseVirtualRow: ITechControlDatabase;
    public iTechControlExpressions: ITechControlExpression[];
    public iTechControlTableMaps: ITechControlTableMap[];
}


































