
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechControlStoragePolicy } from "./ITechControlStoragePolicy";
import { ITechControlStoragePolicyVersionToFileType } from "./ITechControlStoragePolicyVersionToFileType";
import { ITechControlStoragePolicyVersionToTreeRootPath } from "./ITechControlStoragePolicyVersionToTreeRootPath";



export class ITechControlStoragePolicyVersion {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public iTechControlStoragePolicyRowId: number | null;
    public sortOrder: number | null;
    public startDate: number | null;
    public endDate: number | null;
    public description: string;
    public abb: string;
    public comment1: string;
    public comment2: string;
    public guid: number[];
    public signature: number[];
    public iTechControlStoragePolicies: ITechControlStoragePolicy[];
    public iTechControlStoragePolicyRow: ITechControlStoragePolicy;
    public iTechControlStoragePolicyVersionToFileTypes: ITechControlStoragePolicyVersionToFileType[];
    public iTechControlStoragePolicyVersionToTreeRootPaths: ITechControlStoragePolicyVersionToTreeRootPath[];
}


































