
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataSecurityObject } from "./ITechDataSecurityObject";



export class ITechDataMembership {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public iTechDataSecurityObjectMemberRowId: number | null;
    public iTechDataSecurityObjectMemberOfRowId: number | null;
    public guid: number[];
    public signature: number[];
    public iTechDataSecurityObjectMemberOfRow: ITechDataSecurityObject;
    public iTechDataSecurityObjectMemberRow: ITechDataSecurityObject;
}


































