
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechDataLicensingPartNumberEnum {
    sipVoiceRecorder = 1,
    tdmVoiceRecorder = 2,
    eCommsRecorder = 3,
    eCommsCapture = 4,
    vCommsCapture = 5,
    voiceTranscription = 6,
    voiceTranslation = 7,
    eCommsTranslation = 8,
    voiceEdgeDevice = 9,
    eCommsEdgeDevice = 10,
    videoCapture = 11
}

































