
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlReplicateStatusEnum {
    error = -1,
    completed = 1,
    queued = 2,
    held = 3,
    heldWaiting = 4,
    notSupported = 5,
    jeffVrMissing = 6,
    jeffVrMultiple = 7,
    jeffVrReprocess = 8,
    excIdentifierCall = 9
}

































