
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechDataEventStatusEnum {
    newEvent = 1,
    assigned = 2,
    inProgress = 3,
    escalatedToInvestigation = 4,
    closedByAssignee = 5,
    managmentSignOff = 6
}

































