
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebSurveillance implements IRowId {
    
    public rowId: number;
    public gid: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public dateInsertedString: string;
    public dateModifiedString: string;
    public dateArchivedString: string;
    public iTechDataSecurityObjectRowId: number | null;
    public owner: string;
    public name: string;
    public isOrdered: boolean | null;
    public threshold: number | null;
    public timespan: number | null;
    public description: string;
    public comments: string;
    public iTechDataRiskTypeRowId: number | null;
    public riskType: string;
    public iTechDataRiskCategoryTypeRowId: number | null;
    public riskCategory: string;
    public riskCategoryDescription: string;
    public iTechDataScenarioTypeRowId: number | null;
    public scenarioType: string;
    public iTechDataUserMemberOfRowId: number | null;
    public disabled: boolean;
    public scenarioTypeDescription: string;
    public ruleCount: number | null;
    public alertCount: number | null;
    public filterCount: number;
    public userCount: number | null;
    public groups: string;
}


































