
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlSourceEnum {
    fileAndFolder = 1,
    database = 2,
    email = 3,
    fax = 4,
    im = 5,
    logFiles = 6,
    print = 7,
    scannedDocuments = 8,
    sharePoint = 9,
    sms = 10,
    videoConferencing = 11,
    mobileVoice = 12,
    fixedLineVoice = 13,
    goodTalk = 14,
    goodChat = 15,
    skypeVoice = 16,
    skypeIM = 17,
    byodVoice = 18
}

































