
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechDataSecurityObjectEnum {
    unknown = 1,
    user = 2,
    group = 3,
    host = 4,
    sharedLine = 5,
    sharedMailbox = 6,
    distributionList = 7,
    primary = 8,
    secondary = 9,
    sdm = 10,
    service = 11,
    retentionGroup = 12,
    voicemail = 13,
    externalUser = 14
}

































