
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class ITechDataDpia {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public guid: number[];
    public signature: number[];
    public projectName: string;
    public practiceName: string;
    public reason: string;
    public personName: string;
    public dateSubmission: string;
    public dateApproval: string;
    public approvedBy: string;
    public businessPurpose: string;
    public dataProcessing: string;
    public dataLocations: string;
    public personalData: boolean | null;
    public summary: string;
    public dataType: string;
    public dataSubjectCount: string;
    public personalDataTypes: string;
    public specialCategoryTypes: string;
    public highRiskTypes: string;
    public personalDataCollection: string;
    public privacyNoticeStatus: string;
    public personalDataUsage: string;
    public personalDataAccuracy: string;
    public lawfulBasis: string;
    public personalDataStorage: string;
    public personalDataLocation: string;
    public subjectDataWithinMonth: string;
    public isAutomated: boolean | null;
    public dataRetention: string;
    public dataDisposal: string;
    public dataAccess: string;
    public isTrainingRelevant: boolean | null;
    public isTrainingWithinYear: boolean | null;
    public authenticationMethods: string;
    public monitoringData: string;
    public personalDataIntegrity: string;
    public isDataTransferOutside: boolean | null;
    public isController: boolean | null;
    public recipients: string;
    public transferMethod: string;
    public isOutsideEea: boolean | null;
    public countries: string;
    public transferConditions: string;
    public privacyIssues: string;
    public risks: string;
    public solutions: string;
    public results: string;
    public actionOwners: string;
    public targetDates: string;
    public additionalInformation: string;
    public projectLead: string;
    public criminalConvictions: boolean | null;
}


































