
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebRule implements IRowId {
    
    public rowId: number;
    public gid: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public dateInsertedString: string;
    public dateModifiedString: string;
    public dateArchivedString: string;
    public iTechDataSecurityObjectRowId: number | null;
    public owner: string;
    public name: string;
    public json: string;
    public iTechDataRuleTypeRowId: number | null;
    public ruleType: string;
    public disabled: boolean;
    public userCount: number | null;
    public taskCount: number | null;
    public filterCount: number;
    public parts: string;
    public policies: string;
    public policyCount: number | null;
}


































