
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebUser implements IRowId {
    
    public rowId: number;
    public name: string;
    public username: string;
    public onLegalHold: boolean;
    public dateInserted: number | null;
    public dateArchived: number | null;
    public dateInsertedString: string;
    public dateArchivedString: string;
    public truSubscriberId: number | null;
    public iTechDataUserMemberOfRowId: number | null;
    public identifiers: string;
    public groups: string;
    public userGroups: string;
    public totalCases: number | null;
    public openCases: number | null;
    public collectionJson: string;
    public gid: number;
}


































