
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebHierarchy implements IRowId {
    
    public iTechDataUserRowId: number;
    public userName: string;
    public riskRating: number | null;
    public roleStartDateString: string;
    public roleName: string;
    public roleType: string;
    public roleLocation: string;
    public rowId: number;
    public level: number;
}


































