
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechControlMap } from "./ITechControlMap";
import { ITechControlOperation } from "./ITechControlOperation";
import { ITechControlRuleType } from "./ITechControlRuleType";



export class ITechControlExpression {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public guid: number[];
    public signature: number[];
    public iTechControlMapRowId: number | null;
    public iTechControlExpressionParentRowId: number | null;
    public iTechControlRuleTypeRowId: number | null;
    public iTechControlExpressionParentRow: ITechControlExpression;
    public iTechControlMapRow: ITechControlMap;
    public iTechControlOperations: ITechControlOperation[];
    public iTechControlRuleTypeRow: ITechControlRuleType;
    public inverseITechControlExpressionParentRow: ITechControlExpression[];
}


































