
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class ITechWebRopaMappingRegister {
    
    public rowId: number;
    public gid: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public source: string;
    public personalData: string;
    public reason: string;
    public disposal: string;
    public datastore: string;
    public processMethod: string;
    public accessRights: string;
    public relationshipReference: number | null;
    public dateInsertedString: string;
    public dateModifiedString: string;
    public dateArchivedString: string;
}


































