
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebCollectionService implements IRowId {
    
    public rowId: number;
    public gid: number;
    public hostsToServiceTypeNotes: string;
    public hostsToServiceTypeArgs: string;
    public hostsToServiceRestartInterval: number | null;
    public hostsToServiceInterval: number | null;
    public hostsToServiceMinRunTime: number | null;
    public iTechControlHostServiceTypeRowId: number | null;
    public hostServiceTypeAbb: string;
    public hostServiceTypeDescription: string;
    public iTechControlHostRowId: number;
    public fqHostName: string;
    public iTechControlProcessGridRowId: number | null;
    public location: string;
    public actionCount: number | null;
    public errorCount: number | null;
    public startOnLoad: string;
    public resetHolder: string;
    public iTechControlDatabaseRowId: number | null;
    public databaseName: string;
    public connectionString: string;
    public folderName: string;
    public databaseDetails: string;
    public loginName: string;
    public password: string;
    public databaseRestartMinInterval: number | null;
    public databaseRestartInterval: number | null;
    public databaseMaxRunTime: number | null;
    public dateInsertedDatabase: number | null;
    public dateInsertedDatabaseString: string;
    public dateModifiedDatabase: number | null;
    public dateModifiedDatabaseString: string;
    public customArgs: string;
    public decryptionPrivateKey: string;
    public iTechControlGlobalRowId: number | null;
    public globalName: string;
    public globalValidUrls: string;
    public skin: string;
    public hasPrivateWebsite: boolean | null;
    public iTechControlRegionRowId: number | null;
    public regionName: string;
    public iTechControlDatabaseTypeRowId: number | null;
    public databaseTypeAbb: string;
    public databaseTypeDescription: string;
    public iTechControlDatabaseSchemaTypeRowId: number | null;
    public schemaTypeAbb: string;
    public schemaDescription: string;
    public auditIncluded: boolean | null;
    public iTechControlServiceRowId: number | null;
    public serviceName: string;
    public iTechControlServiceTypeRowId: number | null;
    public serviceTypeAbb: string;
    public serviceTypeDescription: string;
    public iTechControlHolderActionRestartTypeRowId: number | null;
    public holderRestartTypeAbb: string;
    public holderRestartTypeDescription: string;
}


































