
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebTerm implements IRowId {
    
    public rowId: number;
    public gid: number;
    public iTechDataTermTypeRowId: number | null;
    public iTechDataFilterTypeRowId: number | null;
    public iTechDataWebFilterRowId: number | null;
    public addToAllCases: boolean;
    public term: string;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public dateInsertedString: string;
    public dateModifiedString: string;
    public dateArchivedString: string;
    public termType: string;
    public termTypeDescription: string;
    public filterType: string;
    public filterTypeDescription: string;
    public iTechDataWebFilterJson: string;
    public iTechControlTableReferenceRowId: number | null;
    public iTechControlTableReferenceTypeRowId: number | null;
    public json: string;
}


































