
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataSecurityObject } from "./ITechDataSecurityObject";
import { ITechDataUserIdentifierType } from "./ITechDataUserIdentifierType";
import { ITechDataUser } from "./ITechDataUser";
import { ITechDataUserIdentifierToCollectionType } from "./ITechDataUserIdentifierToCollectionType";



export class ITechDataUserIdentifier {
    
    public rowId: number;
    public isIdentifierHidden: boolean | null;
    public identifier: string;
    public displayAs: string;
    public disabled: boolean | null;
    public isChargeable: boolean | null;
    public ported: boolean | null;
    public sourceGuid: number[];
    public guid: number[];
    public signature: number[];
    public iTechControlGlobalRowId: number | null;
    public iTechControlRegionRowId: number | null;
    public iTechControlRetentionPolicyRowId: number | null;
    public iTechControlContractRowId: number | null;
    public iTechDataUserIdentifierTypeRowId: number | null;
    public iTechDataUserIdentifierParentRowId: number | null;
    public iTechDataSecurityObjectRowId: number | null;
    public iTechDataUserRowId: number | null;
    public iTechDataUserIdentifierGlobalRowId: number | null;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public dateActivated: number | null;
    public dateReconciled: number | null;
    public status: number[];
    public authorisationRulesBinary: number[];
    public args: string;
    public iTechControlVoiceTranslationMethodTypeRowId: number | null;
    public iTechControlVoiceToTextEngineTypeRowId: number | null;
    public iTechControlIdentifierSourceSystemTypeRowId: number | null;
    public iTechDataSecurityObjectRow: ITechDataSecurityObject;
    public iTechDataUserIdentifierParentRow: ITechDataUserIdentifier;
    public iTechDataUserIdentifierTypeRow: ITechDataUserIdentifierType;
    public iTechDataUserRow: ITechDataUser;
    public inverseITechDataUserIdentifierParentRow: ITechDataUserIdentifier[];
    public iTechDataUserIdentifierToCollectionTypes: ITechDataUserIdentifierToCollectionType[];
}


































