
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataSecurityObject } from "./ITechDataSecurityObject";



export class ITechDataNote {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public guid: number[];
    public signature: number[];
    public iTechDataSecurityObjectRowId: number | null;
    public body: string;
    public dateStart: number | null;
    public dateEnd: number | null;
    public noteType: string;
    public iTechDataCaseRowId: number | null;
    public title: string;
    public iTechDataNoteTypeRowId: number | null;
    public documentGuid: number[];
    public iTechDataNoteParentRowId: number | null;
    public iTechDataSecurityObjectRow: ITechDataSecurityObject;
}


































