
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechDataAssureCallQualityEnum {
    gt90percentDtmf = 1,
    lossBeginning = 2,
    lossEnd = 3,
    gt80lt90percent = 4,
    gt70lt80percent = 5,
    failedLt70percent = 6,
    notTested = 7,
    vmSuccessful = 8,
    reTest = 9
}

































