
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechControlDatabase } from "./ITechControlDatabase";
import { ITechControlHost } from "./ITechControlHost";
import { ITechControlHostServiceType } from "./ITechControlHostServiceType";
import { ITechControlService } from "./ITechControlService";
import { ITechControlServiceType } from "./ITechControlServiceType";



export class ITechControlServicesToHostsToServiceTypeToDatabase {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public iTechControlHostRowId: number | null;
    public iTechControlDatabaseRowId: number | null;
    public iTechControlServiceTypeRowId: number | null;
    public iTechControlServiceTypeSubRowId: number | null;
    public regionPreferredWeighting: number | null;
    public iTechControlServiceRowId: number | null;
    public args: string;
    public notes: string;
    public iTechControlHostServiceTypeRowId: number | null;
    public startOnLoad: boolean | null;
    public resetActionHolderOnStart: boolean | null;
    public serviceIntervalResetActionSeconds: number | null;
    public iTechControlHolderActionRestartTypeRowId: number | null;
    public restartMinInterval: number | null;
    public restartInterval: number | null;
    public maxRunTime: number | null;
    public stTime: number | null;
    public edTime: number | null;
    public sleepInterval: number | null;
    public mergeIntervalSeconds: number | null;
    public maxRamSizeBytes: number | null;
    public mergeLoopCount: number | null;
    public guid: number[];
    public signature: number[];
    public serviceIntervalResetAction: number | null;
    public isManaged: boolean | null;
    public iTechControlServiceStatusTypeRequestedRowId: number | null;
    public iTechControlServiceStatusTypeCurrentRowId: number | null;
    public iTechControlDatabaseRow: ITechControlDatabase;
    public iTechControlHostRow: ITechControlHost;
    public iTechControlHostServiceTypeRow: ITechControlHostServiceType;
    public iTechControlServiceRow: ITechControlService;
    public iTechControlServiceTypeRow: ITechControlServiceType;
}


































