
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebReport implements IRowId {
    
    public rowId: number;
    public gid: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public fileName: string;
    public blob: number[];
    public iTechDataWebReportConfigurationRowId: number | null;
    public tab: string;
    public dateInsertedString: string;
    public dateModifiedString: string;
    public dateArchivedString: string;
    public owner: string;
    public schedule: string;
    public iTechDataSecurityObjectRowId: number | null;
    public iTechDataWebTabRowId: number | null;
}


































