
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class ITechControlHolderActionRestartType {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public abb: string;
    public description: string;
    public stTime: number | null;
    public edTime: number | null;
    public weekendProcessing: boolean | null;
    public daysOfTheWeek: string;
    public minPauseSeconds: boolean | null;
    public guid: number[];
    public signature: number[];
}


































