
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class ITechControlCountryCodeType {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public description: string;
    public abb: string;
    public iTechControlCountryCodeTypeParentRowId: number | null;
    public isMobile: boolean | null;
    public validated: Date | null;
    public guid: number[];
    public signature: number[];
    public iTechControlCountryCodeTypeParentRow: ITechControlCountryCodeType;
    public inverseITechControlCountryCodeTypeParentRow: ITechControlCountryCodeType[];
}


































