
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechControlServiceType } from "./ITechControlServiceType";
import { ITechControlServicesToHostsToServiceTypeToDatabase } from "./ITechControlServicesToHostsToServiceTypeToDatabase";



export class ITechControlService {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public serviceName: string;
    public iTechControlServiceTypeRowId: number | null;
    public guid: number[];
    public signature: number[];
    public iTechControlServiceTypeRow: ITechControlServiceType;
    public iTechControlServicesToHostsToServiceTypeToDatabases: ITechControlServicesToHostsToServiceTypeToDatabase[];
}


































