
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataCaseStatusToSubTypeLookup } from "./ITechDataCaseStatusToSubTypeLookup";



export class ITechDataCaseStatusType {
    
    public rowId: number;
    public abb: string;
    public description: string;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public guid: number[];
    public signature: number[];
    public iTechDataCaseStatusToSubTypeLookups: ITechDataCaseStatusToSubTypeLookup[];
}


































