
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataWebTab } from "./ITechDataWebTab";
import { ITechDataWebTemplate } from "./ITechDataWebTemplate";



export class ITechDataWebComponent {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public guid: number[];
    public signature: number[];
    public iTechDataWebTabRowId: number | null;
    public json: string;
    public x: number | null;
    public y: number | null;
    public h: number | null;
    public w: number | null;
    public iTechDataWebComponentTypeRowId: number | null;
    public iTechDataWebTemplateRowId: number | null;
    public iTechDataWebTabRow: ITechDataWebTab;
    public iTechDataWebTemplateRow: ITechDataWebTemplate;
}


































