
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechDataManageObjectStatusEnum {
    run = 1,
    pause = 2,
    restart = 3,
    forceObjectUpdate = 4,
    softwareUpdate = 5,
    disabledManually = 6,
    poweredOffManually = 7
}

































