
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlKeyDataEnum {
    reference = 1,
    boolean = 2,
    byte = 3,
    short = 4,
    int = 5,
    long = 6,
    float = 7,
    double = 8,
    dateTime = 9,
    string = 10,
    custom = 11,
    byteArray = 12
}

































