
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebAudit implements IRowId {
    
    public id: string | null;
    public gid: string;
    public rowId: number;
    public dateInsertedString: string;
    public dateInserted: number | null;
    public dateModifiedString: string;
    public dateModified: number | null;
    public iTechControlAuditCategoryTypeRowId: number | null;
    public iTechControlAuditCategoryTypeDescription: string;
    public iTechControlAuditEventTypeRowId: number | null;
    public iTechControlEventTypeDescription: string;
    public iTechControlAuditSeverityTypeRowId: number | null;
    public iTechControlAuditSeverityTypeDescription: string;
    public iTechAuditId: number | null;
    public iTechDataSecurityObjectRowId: number | null;
    public iTechDataSecurityObject: string;
    public summary: string;
    public publicIpAddress: string;
    public iTechDataCaseRowId: number | null;
    public iTechSimRowId: number | null;
    public iTechControlTableReferenceTypeRowId: number | null;
    public iTechControlTableReferenceRowId: number | null;
}


































