
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechControlDataStoreType } from "./ITechControlDataStoreType";
import { ITechControlDatabase } from "./ITechControlDatabase";
import { ITechControlHost } from "./ITechControlHost";
import { ITechControlRegion } from "./ITechControlRegion";
import { ITechControlStoragePolicyVersionToTreeRootPath } from "./ITechControlStoragePolicyVersionToTreeRootPath";
import { ITechControlTreeStructure } from "./ITechControlTreeStructure";



export class ITechControlTreeRootPath {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public iTechControlRegionRowId: number | null;
    public iTechControlDataStoreTypeRowId: number | null;
    public iTechControlHostRowId: number | null;
    public path: string;
    public iTechControlDatabaseRowId: number | null;
    public iTechControlTreeRootPathGroupId: number | null;
    public guid: number[];
    public signature: number[];
    public iTechControlDataStoreTypeRow: ITechControlDataStoreType;
    public iTechControlDatabaseRow: ITechControlDatabase;
    public iTechControlHostRow: ITechControlHost;
    public iTechControlHostRowNavigation: ITechControlRegion;
    public iTechControlStoragePolicyVersionToTreeRootPaths: ITechControlStoragePolicyVersionToTreeRootPath[];
    public iTechControlTreeStructures: ITechControlTreeStructure[];
}


































