
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlSearchEnum {
    summary = 1,
    fromAddress = 2,
    toAddress = 3,
    name = 4,
    body = 5,
    bloombergAutomated = 6,
    reutersDisclaimer = 7,
    childBody = 8,
    owner = 9,
    relativePath = 10
}

































