
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlTreeNodeEnum {
    globalRoot = 1,
    region = 2,
    fileAndFolder = 3,
    emailStore = 4,
    mobile = 5,
    host = 6,
    drive = 7,
    folder = 8,
    file = 9,
    user = 10,
    mailbox = 11,
    email = 12,
    voice = 13,
    presence = 14,
    sms = 15,
    sharePoint = 16,
    unassigned = 17,
    assigned = 18,
    discarded = 19,
    videoConf = 20,
    database = 21,
    fax = 22,
    paperDoc = 23,
    logFiles = 24,
    externalDocs = 25,
    print = 26,
    company = 27,
    bbIMStore = 28,
    fixedLineStore = 29,
    goodTalk = 30,
    goodChat = 31,
    skype = 32,
    symphony = 33,
    skypeVoice = 34,
    skypeIM = 35,
    reutersIM = 36,
    turret = 37,
    tmlim = 38,
    tmlVoice = 39
}

































