
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataMembership } from "./ITechDataMembership";
import { ITechDataNote } from "./ITechDataNote";
import { ITechDataSecurityObjectSourceType } from "./ITechDataSecurityObjectSourceType";
import { ITechDataSecurityObjectType } from "./ITechDataSecurityObjectType";
import { ITechDataUserIdentifier } from "./ITechDataUserIdentifier";
import { ITechDataUser } from "./ITechDataUser";



export class ITechDataSecurityObject {
    
    public rowId: number;
    public dateActivated: number | null;
    public datePasswordChanged: number | null;
    public status: number[];
    public forename: string;
    public surname: string;
    public title: string;
    public isCollection: boolean | null;
    public isLogin: boolean | null;
    public accountDisabled: string;
    public isViewable: boolean | null;
    public isEditable: boolean | null;
    public onLegalHold: boolean | null;
    public username: string;
    public displayName: string;
    public guid: number[];
    public signature: number[];
    public password: string;
    public sidFromSource: string;
    public guidFromSource: string;
    public x500CanonicalName: string;
    public iTechReportingContractElementDiskRowId: number | null;
    public iTechReportingContractElementUserRowId: number | null;
    public skin: string;
    public timeoutTicks: number | null;
    public truSubscriberId: number | null;
    public truQuoteReference: string;
    public truBlackberry: boolean | null;
    public isTemplate: boolean | null;
    public isChargeable: boolean | null;
    public dateReconciled: number | null;
    public timezone: string;
    public dateExpired: number | null;
    public encryptionKey: number[];
    public defaultObjectAuthorisationRulesBinary: number[];
    public iTechControlGlobalRowId: number | null;
    public iTechControlRegionRowId: number | null;
    public iTechControlRetentionPolicyRowId: number | null;
    public iTechControlContractRowId: number | null;
    public iTechDataSecurityObjectGlobalRowId: number | null;
    public iTechDataSecurityObjectSourceTypeRowId: number | null;
    public iTechDataSecurityObjectTypeRowId: number | null;
    public iTechDataSecurityObjectParentRowId: number | null;
    public iTechSimFolderGuid: number[];
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public sessionDate: number | null;
    public passwordAttempts: number | null;
    public voiceMail: boolean | null;
    public maxNumberCalls: number | null;
    public busyOption: string;
    public description: string;
    public dualAuthenticationDate: number | null;
    public dualAuthenticationCode: string;
    public dateChallenged: number | null;
    public iTechDataActionRowId: number | null;
    public iTechDataWebTabRowId: number | null;
    public isVendor: boolean | null;
    public iTechDataAuthTypeRowId: number | null;
    public iTechDataMembershipITechDataSecurityObjectMemberOfRows: ITechDataMembership[];
    public iTechDataMembershipITechDataSecurityObjectMemberRows: ITechDataMembership[];
    public iTechDataNotes: ITechDataNote[];
    public iTechDataSecurityObjectParentRow: ITechDataSecurityObject;
    public iTechDataSecurityObjectSourceTypeRow: ITechDataSecurityObjectSourceType;
    public iTechDataSecurityObjectTypeRow: ITechDataSecurityObjectType;
    public iTechDataUserIdentifiers: ITechDataUserIdentifier[];
    public inverseITechDataSecurityObjectParentRow: ITechDataSecurityObject[];
    public iTechDataUsers: ITechDataUser[];
}


































