
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlSimFsiOptionsEnum {
    default = 1,
    copyDiskUnencrypted = 2,
    createPDF = 4,
    createMP3Single = 8,
    createMP4Single = 16,
    createMP3Merged = 32,
    createMP4Merged = 64
}

































