
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechDataAssureIdentifierStatusTestEnum {
    successful = 1,
    resetForTest = 2,
    answeredWaitAnalysis = 3,
    noConnection = 4,
    noAnswer = 5,
    noDoesNotExist = 6,
    notTested = 7,
    vmSuccessful = 8,
    reTest = 9,
    failedLastTest = 10,
    noTestRequired = 11
}

































