
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechDataAssureSourceSystemEnum {
    cisco = 1,
    mitel = 2,
    cloudCall = 3,
    _8x8 = 4,
    truphone = 5,
    _3cx = 6,
    skype = 7,
    teams = 8,
    movius = 9,
    teleware = 10,
    teleMessage = 11,
    whatsApp = 12,
    ringCentral = 13,
    unigy = 14
}

































