
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class ITechAuditView {
    
    public id: string;
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public iTechControlAuditCategoryTypeRowId: number | null;
    public iTechControlAuditEventTypeRowId: number | null;
    public iTechControlAuditSeverityTypeRowId: number | null;
    public iTechAuditId: number | null;
    public iTechDataUserRowId: number | null;
    public iTechDataSecurityObjectRowId: number | null;
    public iTechControlHostRowId: number | null;
    public summary: string;
    public argumentGuid: number[];
    public guid: number[];
    public signature: number[];
    public publicIpAddress: string;
}


































