
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechControlDataStoreTypeToKeyType } from "./ITechControlDataStoreTypeToKeyType";
import { ITechControlFileTypeToKeyType } from "./ITechControlFileTypeToKeyType";
import { ITechControlKeyDataType } from "./ITechControlKeyDataType";



export class ITechControlKeyType {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public abb: string;
    public description: string;
    public iTechControlKeyDataTypeRowId: number | null;
    public columnName: string;
    public guid: number[];
    public signature: number[];
    public web: string;
    public iTechControlDataStoreTypeToKeyTypes: ITechControlDataStoreTypeToKeyType[];
    public iTechControlFileTypeToKeyTypes: ITechControlFileTypeToKeyType[];
    public iTechControlKeyDataTypeRow: ITechControlKeyDataType;
}


































