
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechControlDatabase } from "./ITechControlDatabase";
import { ITechControlGlobal } from "./ITechControlGlobal";
import { ITechControlHost } from "./ITechControlHost";
import { ITechControlTreeRootPath } from "./ITechControlTreeRootPath";



export class ITechControlRegion {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public iTechControlGlobalRowId: number | null;
    public name: string;
    public iTechControlRegionParentRowId: number | null;
    public guid: number[];
    public signature: number[];
    public dateLastRetentionDeletion: number | null;
    public iTechControlProcessGridRowId: number | null;
    public alertUrl: string;
    public reIndexInProgress: boolean | null;
    public args: string;
    public iTechControlDatabases: ITechControlDatabase[];
    public iTechControlGlobalRow: ITechControlGlobal;
    public iTechControlHosts: ITechControlHost[];
    public iTechControlRegionParentRow: ITechControlRegion;
    public iTechControlTreeRootPaths: ITechControlTreeRootPath[];
    public inverseITechControlRegionParentRow: ITechControlRegion[];
}


































