
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class ITechDataArea {
    
    public rowId: number;
    public pageNumber: number | null;
    public x1: number | null;
    public x2: number | null;
    public x3: number | null;
    public x4: number | null;
    public y1: number | null;
    public y2: number | null;
    public y3: number | null;
    public y4: number | null;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
}


































