
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class ITechWebSimCaseFileUser {
    
    public rowId: number;
    public name: string;
    public fromCount: number;
    public toCount: number;
    public ownerCount: number;
    public onLegalHold: boolean | null;
    public dateInserted: number | null;
    public dateInsertedString: string;
    public identifiers: string;
    public gid: number;
}


































