
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechControlTable } from "./ITechControlTable";
import { ITechType } from "./ITechType";
import { IColumnName } from "./IColumnName";



export class ITechControlColumn implements IColumnName {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public guid: number[];
    public signature: number[];
    public iTechControlTableRowId: number | null;
    public iTechControlColumnTypeRowId: number | null;
    public name: string;
    public description: string;
    public gridIndex: number | null;
    public gridSelected: boolean | null;
    public minWidth: number | null;
    public helperText: string;
    public treeIndex: number | null;
    public treeSelected: boolean | null;
    public notes: string;
    public advancedFilterSelected: boolean | null;
    public isDynamicDate: boolean | null;
    public isLogin: boolean | null;
    public iTechControlTableRow: ITechControlTable;
    public types: ITechType[];
}


































