
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebTaskOwner implements IRowId {
    
    public rowId: number;
    public gid: number;
    public ownerRowId: number | null;
    public ownerName: string;
    public ownerUsername: string;
    public iTechControlTableReferenceRowId: number | null;
    public iTechControlTableReferenceTypeRowId: number | null;
    public dateStartActualString: string;
    public dateStartScheduledString: string;
    public taskName: string;
    public taskStatusTypeDescription: string;
    public taskTypeDescription: string;
    public dateAssignedToTaskString: string;
    public dateTaskArchivedString: string;
}


































