
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebTask implements IRowId {
    
    public rowId: number;
    public gid: number;
    public taskName: string;
    public isTemplate: boolean | null;
    public iTechDataTaskRootRowId: number | null;
    public iTechDataTaskParentRowId: number | null;
    public iTechDataTaskPredessorRowId: number | null;
    public iTechDataTaskTypeRowId: number | null;
    public iTechDataTaskStatusTypeRowId: number | null;
    public name: string;
    public taskDetails: string;
    public percentageComplete: number | null;
    public dateStartScheduled: number | null;
    public durationMinScheduled: number | null;
    public dateStartActual: number | null;
    public durationMinActual: number | null;
    public hasPredessor: boolean | null;
    public predessorRowId: number | null;
    public args: string;
    public iTechControlTableReferenceTypeChildRowId: number | null;
    public riskRatingManual: number | null;
    public riskRatingMl01: number | null;
    public riskRatingMl02: number | null;
    public priorityManual: number | null;
    public outcomeNotes: string;
    public taskType: string;
    public taskTypeDescription: string;
    public taskStatusType: string;
    public taskStatusTypeDescription: string;
    public dateStartActualString: string;
    public dateStartScheduledString: string;
    public ownerName: string;
    public ownerUsername: string;
    public ownerRowId: number | null;
    public dateAssignedToTask: number | null;
    public dateTaskArchived: number | null;
    public dateAssignedToTaskString: string;
    public dateTaskArchivedString: string;
    public iTechDataTaskOutcomeTypeRowId: number | null;
    public outcomeType: string;
    public outcomeTypeDescription: string;
    public iTechControlTableReferenceRowId: number | null;
    public iTechControlTableReferenceTypeRowId: number | null;
    public ownerNames: string;
    public dateArchived: number | null;
    public hierarchy: any;
    public dateDue: number | null;
    public dateDueString: string;
}


































