
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlDatabaseEnum {
    sqlServer = 1,
    oracle = 2,
    odbc = 3,
    ole = 4,
    snaplock = 5,
    centera = 6,
    ntfs = 7,
    iTech = 8,
    imap = 9,
    ntfsWatcher = 10,
    obsidianSMS = 11,
    ocrCatcher = 12,
    videoCatcher = 13,
    ntfsGeneric = 14,
    lDap = 15,
    mobileDataImap = 16,
    oP3Nvoice = 17,
    deleted = 18,
    solrLucene = 19,
    web = 20
}

































