
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class ITechDataResultSet {
    
    public rowId: number;
    public name: string;
    public iTechDataSecurityObjectRowId: number | null;
    public iTechDataTableReferenceRowId: number | null;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
}


































