
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechControlTreeNodeType } from "./ITechControlTreeNodeType";
import { ITechControlTreeRootPath } from "./ITechControlTreeRootPath";



export class ITechControlTreeStructure {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public name: string;
    public iTechControlGlobalRowId: number | null;
    public iTechControlRegionRowId: number | null;
    public iTechControlTreeStructureParentRowId: number | null;
    public iTechControlTreeRootPathGroupId: number | null;
    public iTechControlTreeRootPathRowId: number | null;
    public iTechControlTreeNodeTypeRowId: number | null;
    public guid: number[];
    public signature: number[];
    public hasChildFolders: boolean | null;
    public relativePath: string;
    public iTechControlTreeNodeTypeRow: ITechControlTreeNodeType;
    public iTechControlTreeRootPathRow: ITechControlTreeRootPath;
    public iTechControlTreeStructureParentRow: ITechControlTreeStructure;
    public inverseITechControlTreeStructureParentRow: ITechControlTreeStructure[];
}


































