
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlTrackingStatusEnum {
    simSwapProvisioning = 1,
    newUserProvisioing = 2,
    recorderFailure = 3,
    voiceCallLoss = 4,
    noTruSMS = 5,
    smsTimeshift = 6,
    smsReconciliation = 7,
    smsLoss = 8,
    reconciled = 9,
    unmatched = 10,
    camelNonRecorded = 11
}

































