
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
import { ITechDataWebMenu } from "./ITechDataWebMenu";




export class ITechDataWebFolder {
    
    public iTechDataWebMenus: ITechDataWebMenu[];
    public iTechDataWebFolders: ITechDataWebFolder[];
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public guid: number[];
    public signature: number[];
    public name: string;
    public iTechDataWebFolderParentRowId: number | null;
    public iTechDataCaseRowId: number | null;
    public hierarchy: any;
    public iTechDataSecurityObjectRowId: number | null;
    public iTechDataWebFolderTypeRowId: number | null;
}


































