
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebCollectionQueue implements IRowId {
    
    public startOnLoad: boolean | null;
    public queueSize: number | null;
    public hostToServiceTypeToDatabaseArgs: string;
    public serviceTypeDescription: string;
    public databaseName: string;
    public fqHostName: string;
    public iTechControlServiceTypeRowId: number | null;
    public iTechControlDatabaseRowId: number | null;
    public iTechControlHostRowId: number | null;
    public databaseDetails: string;
    public iTechControlServicesToHostsToServiceTypeToDatabaseRowId: number | null;
    public hostToServiceTypeToDatabaseNotes: string;
    public gid: string;
    public rowId: number;
}


































