
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechDataPermissionEnum {
    printResults = 1,
    printContent = 2,
    recoverSingle = 3,
    recoverBulk = 4,
    eDiscoveryBasic = 5,
    viewAudit = 6,
    preview = 7,
    recoverToExchange = 8,
    recoverToShare = 9,
    viewPermissions = 10,
    viewHistory = 11,
    advancedSearch = 12,
    administration = 13,
    policies = 14,
    recoverToZip = 15,
    exploreSearch = 16,
    eDiscoveryStandard = 17,
    recoverOnlyPDF = 18,
    reporting = 19,
    backup = 20,
    viewAuditGlobal = 21,
    kis = 22,
    tracking = 23,
    adminReadOnly = 24,
    explore = 25,
    viewLegalHold = 26,
    enableLegalHold = 27,
    disableLegalHold = 28,
    resetPasswordOnly = 29,
    workflowGlobal = 30,
    workflowRetention = 31,
    workflowUser = 32,
    recordingKIS = 33,
    recordingLegalHold = 34,
    recordingResetPassword = 35,
    recordingAdministration = 36,
    recordingRetention = 37,
    compliance = 38,
    superUser = 39
}

































