
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlKeyEnum {
    dateArchived = 1,
    dateCreated = 2,
    ownerId = 3,
    fileTypeId = 4,
    sourceHostId = 5,
    clientId = 6,
    clientEngagementId = 7,
    automaticRetentionPolicy = 8,
    manualRetentionPolicy = 9,
    from = 10,
    to = 11,
    fileName = 12,
    messageId = 13,
    dateModified = 14,
    auditCategoryId = 15,
    auditEventId = 16,
    auditSeverityId = 17,
    dataStoreId = 18,
    regionId = 19,
    dateInserted = 20,
    file = 21,
    ownerName = 22,
    fileExtension = 23,
    path = 24,
    clientName = 25,
    region = 26,
    sourceHostName = 27,
    fileId = 28,
    relativePath = 29,
    sourceTypeId = 30,
    summary = 31,
    obDateCreated = 32,
    obDateModified = 33,
    obDateDeleted = 34,
    fileSize = 35,
    sourceDatabase = 36,
    retentionPolicy = 37,
    classificationPolicy = 38,
    hasAttachment = 39,
    isInbound = 40,
    caseFileStatus = 41,
    duration = 42,
    group = 43,
    securityObject = 44
}

































