
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebCaseManagement implements IRowId {
    
    public rowId: number;
    public gid: number;
    public name: string;
    public summary: string;
    public iTechDataCaseStatusTypeRowId: number | null;
    public caseStatusTypeAbb: string;
    public caseStatusTypeDescription: string;
    public iTechDataSecurityObjectRowId: number | null;
    public securityObject: string;
    public iTechDataCaseParentRowId: number | null;
    public iTechDataInvestigatorSecurityObjectRowId: number | null;
    public investigator: string;
    public iTechDataCaseTypeRowId: number | null;
    public caseTypeAbb: string;
    public caseTypeDescription: string;
    public iTechDataCaseSubTypeRowId: number | null;
    public caseStatusSubTypeAbb: string;
    public caseStatusSubTypeDescription: string;
    public dateInitiated: number | null;
    public dateInitiatedString: string;
    public caseReference: string;
    public legalHold: boolean | null;
    public dateInserted: number | null;
    public dateInsertedString: string;
    public dateModified: number | null;
    public dateModifiedString: string;
    public dateArchived: number | null;
    public dateArchivedString: string;
    public subjectName: string;
    public subjectEmail: string;
    public subjectMobile: string;
    public subjectPhone: string;
    public subjectAddress: string;
    public dateDue: number | null;
    public dateDueString: string;
    public iTechDataLevelTypeRowId: number | null;
}


































