
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataCompany } from "./ITechDataCompany";
import { ITechDataRole } from "./ITechDataRole";
import { ITechDataUserToRole } from "./ITechDataUserToRole";



export class ITechDataTeam {
    
    public rowId: number;
    public name: string;
    public isExternal: boolean | null;
    public iTechDataCompanyRowId: number | null;
    public description: string;
    public guid: number[];
    public signature: number[];
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public iTechDataCompanyRow: ITechDataCompany;
    public iTechDataRoles: ITechDataRole[];
    public iTechDataUserToRoles: ITechDataUserToRole[];
}


































