
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebReplication implements IRowId {
    
    public rowId: number;
    public gid: string;
    public iTechControlGlobalRowId: number;
    public globalName: string;
    public iTechControlReplicateStatusTypeRowId: number | null;
    public iTechSimReplicateRowId: number;
    public replicationStatusAbb: string;
    public sourceRowId: number;
    public iTechSim: string;
    public obDateCreated: number | null;
    public obDateCreatedString: Date | null;
    public dateReplicated: number | null;
    public dateReplicatedString: Date | null;
    public hoursToReplicate: number | null;
    public iTechControlFileTypeRowId: number | null;
    public fileTypeAbb: string;
    public databaseDetails: string;
    public iTechControlDatabaseSchemaTypeRowId: number | null;
    public databaseSchemaTypeAbb: string;
    public iTechToReplicateRowId: number | null;
    public simName: string;
    public replicateNotes: string;
}


































