
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataCompany } from "./ITechDataCompany";
import { ITechDataRole } from "./ITechDataRole";
import { ITechDataTeam } from "./ITechDataTeam";
import { ITechDataUser } from "./ITechDataUser";



export class ITechDataUserToRole {
    
    public rowId: number;
    public iTechDataUserRowId: number | null;
    public iTechDataRoleRowId: number | null;
    public status: number[];
    public guid: number[];
    public signature: number[];
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public dateActivated: number | null;
    public iTechDataTeamRowId: number | null;
    public iTechDataCompanyRowId: number | null;
    public dateStart: number | null;
    public dateEnd: number | null;
    public riskRating: number | null;
    public iTechDataCompanyRow: ITechDataCompany;
    public iTechDataRoleRow: ITechDataRole;
    public iTechDataTeamRow: ITechDataTeam;
    public iTechDataUserRow: ITechDataUser;
}


































