
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlSimIdentificationFormatEnum {
    default = 1,
    folderName = 2,
    hashFrToSub = 3,
    hashFrToDb = 4,
    hashFrToDbName = 5,
    hashDteDbNameConvId = 6
}

































