
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechDataManageObjectEnum {
    nodeHeader = 1,
    getString = 2,
    getInt32 = 3,
    getDouble = 4,
    getDateTimeTicks = 5,
    setString = 6,
    setInt32 = 7,
    setDouble = 8,
    setDateTimeTicks = 9,
    getStatusField = 10,
    setStatusField = 11
}

































