
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechControlAuditCategoryType } from "./ITechControlAuditCategoryType";
import { ITechControlAuditEventType } from "./ITechControlAuditEventType";
import { ITechControlAuditSeverityType } from "./ITechControlAuditSeverityType";
import { ITechControlHost } from "./ITechControlHost";



export class ITechAudit {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public dateYear: number | null;
    public dateQtr: number | null;
    public dateMonth: number | null;
    public dateWeekOfYear: number | null;
    public dateHour: number | null;
    public dateDay: number | null;
    public dateDayOfWeek: number | null;
    public iTechControlAuditCategoryTypeRowId: number | null;
    public iTechControlAuditEventTypeRowId: number | null;
    public iTechControlAuditSeverityTypeRowId: number | null;
    public iTechAuditId: number | null;
    public iTechDataUserRowId: number | null;
    public iTechDataSecurityObjectRowId: number | null;
    public iTechControlHostRowId: number | null;
    public summary: string;
    public arguments: string;
    public argumentGuid: number[];
    public guid: number[];
    public signature: number[];
    public publicIpAddress: string;
    public requestQuery: string;
    public requestBody: string;
    public iTechDataCaseRowId: number | null;
    public iTechSimRowId: number | null;
    public iTechControlAuditCategoryTypeRow: ITechControlAuditCategoryType;
    public iTechControlAuditEventTypeRow: ITechControlAuditEventType;
    public iTechControlAuditSeverityTypeRow: ITechControlAuditSeverityType;
    public iTechControlHostRow: ITechControlHost;
}


































