
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlSimToFsiEnum {
    rawObject = 1,
    rawMetaData = 2,
    mergedMedia = 3,
    screenShare = 4,
    singleChannel = 5,
    attachment = 6,
    mergedMediaArchived = 7,
    vmSuccessful = 8,
    retest = 9,
    failedLastTest = 10,
    noTestRequired = 11,
    systemNotification = 12,
    pdf = 13,
    pdfStrikeout = 14,
    pdfRedacted = 15,
    mP324kbs = 16
}

































