
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class ITechWebRopa {
    
    public rowId: number;
    public gid: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public businessFunction: string;
    public processingPurpose: string;
    public jointController: string;
    public individualsCategory: string;
    public personalDataCategory: string;
    public recipientCategory: string;
    public contractLink: string;
    public transferLocation: string;
    public transferSafeguards: string;
    public retentionSchedule: string;
    public securityMeasures: string;
    public article6Basis: string;
    public article9Condition: string;
    public processingInterests: string;
    public processingInterestsLink: string;
    public rightsAvailable: string;
    public hasAutomatedDecisionMaking: boolean | null;
    public personalDataSource: string;
    public consentLink: string;
    public dataLocation: string;
    public dpiaRequired: boolean | null;
    public dpiaProgress: string;
    public dpiaLink: string;
    public hasBreachOccurred: boolean | null;
    public breachLink: string;
    public dpaSchedule: string;
    public gdprArticle6Basis: string;
    public retentionErasurePolicyLink: string;
    public retentionErasureCompliance: boolean | null;
    public policyNonAdherenceReason: string;
    public dateInsertedString: string;
    public dateModifiedString: string;
    public dateArchivedString: string;
}


































