
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
import { ITechDataWebFilter } from "./ITechDataWebFilter";




export class ITechDataWebFilterWithUser {
    
    public filter: ITechDataWebFilter;
    public forename: string;
    public surname: string;
    public securityRowId: number | null;
}


































