
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataCaseSubType } from "./ITechDataCaseSubType";
import { ITechDataTaskOutcomeType } from "./ITechDataTaskOutcomeType";
import { ITechDataTaskTypeToOutcome } from "./ITechDataTaskTypeToOutcome";



export class ITechDataTaskOutcome {
    
    public rowId: number;
    public iTechDataTaskOutcomeTypeRowId: number | null;
    public iTechDataCaseSubTypeRowId: number | null;
    public abb: string;
    public description: string;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public guid: number[];
    public signature: number[];
    public iTechDataTaskRowId: number | null;
    public iTechDataCaseSubTypeRow: ITechDataCaseSubType;
    public iTechDataTaskOutcomeTypeRow: ITechDataTaskOutcomeType;
    public iTechDataTaskTypeToOutcomes: ITechDataTaskTypeToOutcome[];
}


































