
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataRoleLocation } from "./ITechDataRoleLocation";
import { ITechDataRoleType } from "./ITechDataRoleType";
import { ITechDataTeam } from "./ITechDataTeam";
import { ITechDataUserToRole } from "./ITechDataUserToRole";



export class ITechDataRole {
    
    public rowId: number;
    public name: string;
    public iTechDataTeamRowId: number | null;
    public description: string;
    public iTechDataRoleLocationRowId: number | null;
    public guid: number[];
    public signature: number[];
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public iTechDataCompanyRowId: number | null;
    public riskRating: number | null;
    public iTechDataRoleTypeRowId: number | null;
    public iTechDataRoleLocationRow: ITechDataRoleLocation;
    public iTechDataRoleTypeRow: ITechDataRoleType;
    public iTechDataTeamRow: ITechDataTeam;
    public iTechDataUserToRoles: ITechDataUserToRole[];
}


































