
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechControlReferenceType } from "./ITechControlReferenceType";



export class ITechControlReference {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public dateActivated: number | null;
    public status: number[];
    public guidParentReference: number[];
    public guidChildReference: number[];
    public iTechControlReferenceTypeRowId: number | null;
    public iTechControlReferenceTypeRow: ITechControlReferenceType;
}


































