
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechDataAssurePolicyEnum {
    voice_Frq_001 = 1,
    voice_AutoTest_R_001 = 2,
    voice_Cdr_001 = 3,
    mobile_Sms_Frq_001 = 4,
    mobile_Sms_AutoTest_R_001 = 5,
    voice_AutoTest_R_QB_001 = 6,
    voice_AutoTest_R_QS_001 = 7
}

































