
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IRowId } from "./IRowId";



export class ITechWebReportingAssure implements IRowId {
    
    public gid: number;
    public rowId: number;
    public detail: string;
    public testCode: string;
    public identifier: string;
    public sourceSystem: string;
    public office: string;
    public device: string;
    public channel: string;
    public lineTestOutcome: string;
    public recorder: string;
    public reason: string;
    public testType: string;
    public policyName: string;
    public qualityMeasure: string;
    public transcript: string;
    public qualityOutcome: string;
    public reportDateLocalTime: Date;
    public reportDateLocalTimeTicks: number | null;
    public reportDateLocalTimeString: string;
    public lastSuccessfulTestDateUtc: Date | null;
    public lastSuccessfulTestDateUtcTicks: number | null;
    public lastSuccessfulTestDateUtcString: string;
    public lastCallDateUtc: Date | null;
    public lastCallDateUtcTicks: number | null;
    public lastCallDateUtcString: string;
    public recordMixName: string;
    public recordingProfileName: string;
    public lineType: string;
    public numPlanOwnerForename: string;
    public numPlanOwnerSurname: string;
    public numPlanOwnerRole: string;
    public deviceOwnerForename: string;
    public deviceOwnerSurname: string;
    public deviceOwnerRole: string;
    public compliantUserStatusCode: string;
    public recordMixDescription: string;
    public noOfRecordingsExpected: number | null;
    public noOfRecordingsFound: number | null;
}


































