
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlServiceEnum {
    collector = 1,
    archive = 2,
    indexer = 3,
    webService = 4,
    actionManager = 5,
    actionStdMan1 = 6,
    diagnostics = 7,
    databaseCheck = 8,
    ntfsCrawler = 9,
    sim = 10,
    imapCrawler = 11,
    ntfsWatcher = 12,
    obsidianSMS = 13,
    reIndexer = 14,
    ocrCapture = 15,
    videoConfCap = 16,
    ntfsGenericWat = 17,
    lDap = 18,
    genericRecover = 19,
    mobileData = 20,
    replicator = 21,
    retentionExp = 22,
    indexMerge = 23,
    deDuplication = 24,
    databaseCache = 25,
    colCleanUp = 26,
    genericDocGen = 27,
    adminPush = 28,
    adminPull = 29,
    normaliseIds001 = 30,
    workflowAdm01 = 31,
    coinoKioskTrn = 32,
    coinoKioskLog = 33,
    coinoSvrHrly = 34,
    coinoSvrEod = 35,
    coinoKioskSec = 36,
    coinoCoin = 37,
    coinoFront = 38,
    coinoBill = 39,
    monitorPerf = 40,
    coinoRate = 41,
    adminGeneral = 42,
    presenceEngine = 43,
    presenceWriter = 44,
    presenceToSip = 45,
    presenceFromSip = 46,
    presenceToVen = 47,
    presenceFromVen = 48,
    presenceEngTo = 49,
    presenceEngFrom = 50,
    adminReporting = 51,
    skypeIm = 52,
    skypeVoice = 53,
    ftpWatcher = 54,
    aiSpeechToTxt01 = 55,
    reIndexerProc = 56,
    serviceDistrib = 57,
    marketData01 = 58,
    zoomVideo = 59,
    smartNumbers = 60,
    launcher = 61,
    slack = 62,
    assureTest01 = 63,
    dataExport = 64,
    assureSched01 = 65,
    policyResolver = 66,
    marketAbSch01 = 67,
    marketAbuse01 = 68,
    pstStandEmail01 = 69,
    ciscoWebex = 70,
    sharePoint01 = 71,
    bloombergExp01 = 72,
    hostCheck = 73,
    ciscoLiTstRes1 = 74,
    unigyLiTstRes1 = 75,
    msGraphApi001 = 76,
    ciscoTestGen001 = 77,
    unigyTestGen001 = 78,
    ciscoFindCdr001 = 79,
    unigyFindCdr001 = 80,
    exportGen001 = 81,
    exportDel001 = 82,
    jeffVrEmpExp001 = 83,
    jeffVrEmpUpl001 = 84,
    jeffVrSynVceRp1 = 85,
    jeffVrSynMbRpt1 = 86,
    jeffVrEmlRpt01 = 87,
    jeffVrRepVce01 = 88,
    jeffVrRptDwn01 = 89,
    jeffVrRepMob01 = 90,
    msTeamsProc001 = 91
}

































