
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataLicensingPartNumber } from "./ITechDataLicensingPartNumber";



export class ITechDataLicensing {
    
    public rowId: number;
    public iTechDataLicensingPartNumberRowId: number | null;
    public quantityPurchased: number | null;
    public dateLicensed: number | null;
    public licenseDurationInMonths: number | null;
    public isAutoRenew: boolean | null;
    public autoRenewOffsetInMonths: number | null;
    public notes: string;
    public purchaseOrderNumber: string;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public guid: number[];
    public signature: number[];
    public iTechDataLicensingPartNumberRow: ITechDataLicensingPartNumber;
}


































