
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlObjectStatusEnum {
    start = 1,
    running = 2,
    stop = 3,
    repeatedError = 4,
    pause = 5,
    halt = 6,
    restart = 7,
    notManaged = 8
}

































