
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class ITechControlIso639Language {
    
    public rowId: number;
    public isoLanguageName: string;
    public nativeName: string;
    public iso639Name: string;
    public iso6392: string;
    public iso6392r: string;
    public iso6393: string;
    public notes: string;
    public notes2: string;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public guid: number[];
}


































