
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class ITechDataAlert {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public guid: number[];
    public signature: number[];
    public iTechDataRuleRowId: number | null;
    public iTechDataCaseRowId: number | null;
    public iTechDataSurveillanceRowId: number | null;
    public score: number | null;
    public detail: string;
    public iTechDataLexiconGroupRowId: number | null;
    public iTechDataRiskTypeRowId: number | null;
    public iTechDataOutcomeTypeRowId: number | null;
    public iTechLinkedRowId: number | null;
    public iTechControlTableReferenceTypeRowId: number | null;
    public triggers: string;
}


































