
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlAuditCategoryEnum {
    user = 100000,
    process = 200000,
    object = 300000,
    recovery = 400000,
    policy = 500000,
    audit = 600000,
    system = 700000,
    security = 800000,
    admin = 900000,
    discovery = 1000000,
    retention = 1100000,
    legalHold = 1200000
}

































