
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataTaskOutcome } from "./ITechDataTaskOutcome";
import { ITechDataTask } from "./ITechDataTask";
import { ITechDataTaskType } from "./ITechDataTaskType";



export class ITechDataTaskTypeToOutcome {
    
    public rowId: number;
    public iTechDataTaskTypeRowId: number | null;
    public iTechDataTaskOutcomeRowId: number | null;
    public iTechDataTaskRowId: number | null;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public guid: number[];
    public signature: number[];
    public iTechDataTaskOutcomeRow: ITechDataTaskOutcome;
    public iTechDataTaskRow: ITechDataTask;
    public iTechDataTaskTypeRow: ITechDataTaskType;
}


































