
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlVoiceToTextEngineEnum {
    notLicensed = 0,
    msofT001 = 1,
    bertinV5001 = 2,
    bertinV6001 = 3,
    bertinV5002 = 4,
    bertinV6002 = 5,
    bertinV6003 = 6,
    bertinV6004 = 7,
    bertinV6005 = 8,
    bertinV6006 = 9,
    bertinV6007 = 10,
    speechmatics001 = 11,
    speechmatics002 = 12,
    mSoftAzure001 = 13,
    speechmaticMaxi001 = 14,
    speechmaticPlus001 = 15,
    intelligentVoice001 = 16
}

































