
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlHolderActionRestartEnum {
    stdRestart = 1,
    busHrsIncWkEnd = 2,
    notBusHrsIncWkEnd = 3,
    dailyAtTheSameTime = 4,
    hourlyAtTheSameTime = 5,
    restartFailed = 6
}

































