
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechControlAuditEventEnum {
    loginSucceeded = 1,
    loginFailed = 2,
    profileApplied = 3,
    folderBrowsed = 4,
    filterApplied = 5,
    logout = 6,
    timeout = 7,
    userAdded = 8,
    userUpdated = 9,
    processStarted = 10,
    processStopped = 11,
    crawlerStarted = 12,
    crawlerEndedNormally = 13,
    crawlerEndedAbnormally = 14,
    archiveStarted = 15,
    archiveEndedNormally = 16,
    archiveEndedAbnormally = 17,
    indexingStarted = 18,
    indexingEndedNormally = 19,
    indexingEndedAbnormally = 20,
    objectCaptured = 21,
    newObject = 22,
    newObjectVersion = 23,
    objectIndexed = 24,
    objectAutoRetentionPolicy = 25,
    objectManualRetentionPolicy = 26,
    objectStubbed = 27,
    objectViewed = 28,
    objectRecovered = 29,
    recoveryRequestReceived = 30,
    recoveryEndedNormally = 31,
    recoveryEndedAbnormally = 32,
    recoveryStarted = 33,
    policyCreated = 34,
    policyUpdated = 35,
    policyExpired = 36,
    userSearchRequest = 37,
    userExploreRequest = 38,
    userAuditSearchRequest = 39,
    userMetadataRequest = 40,
    objectArchived = 41,
    databaseUnavailable = 42,
    applicationEndedAbnormally = 43,
    indexInaccessible = 44,
    actionManagerStarted = 45,
    actionManagerEndedNormally = 46,
    actionManagerEndedAbnormally = 47,
    actionManagerWaiting = 48,
    actionManagerStartingTask = 49,
    databaseAvailable = 50,
    hostAvailable = 51,
    hostUnavailable = 52,
    databaseSyncIssue = 53,
    metadataStarted = 54,
    metadataEndedNormally = 55,
    metadataEndedAbnormally = 56,
    objectDeleted = 57,
    objectAutoClassification = 58,
    objectManualClassification = 59,
    objectOwnerIdentified = 60,
    objectOwnerUnknown = 61,
    actionManagerTaskEnded = 62,
    actionManagerTaskEndedAbnormally = 63,
    userAdminRequest = 64,
    userArchived = 65,
    validationStarted = 66,
    validationEndedNormally = 67,
    validationEndedAbnormally = 68,
    objectCorrupt = 69,
    objectNotification = 70,
    userPermissionModified = 71,
    createDiscovery = 72,
    deleteDiscovery = 73,
    addToDiscovery = 74,
    lockObject = 75,
    releaseObject = 76,
    moveObject = 77,
    userAuditMetadataRequest = 78,
    retentionPolicyDelServiceObjectDeleted = 79,
    retentionPolicyDelServiceSummary = 80,
    retentionPolicyDelServiceStarted = 81,
    retentionPolicyDelServiceEndedNormal = 82,
    retentionPolicyDelServiceEndedAbnormally = 83,
    enableLegalHold = 84,
    disableLegalHold = 85,
    lockUser = 86,
    releaseUser = 87,
    lockGlobal = 88,
    releaseGlobal = 89,
    passwordResetRequest = 90,
    passwordReset = 91
}

































