
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum iTechDataCacheEnum {
    regionDatabase = 1,
    regionSecurityObject = 2,
    regionFileType = 3,
    regionRegion = 4,
    regionTreeRootPath = 5,
    regionPermissionType = 6,
    regionAuditEventType = 7,
    regionAuditCategoryType = 8,
    regionRetentionPolicy = 9,
    regionClassificationPolicy = 10,
    regionUser = 11
}

































