
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechControlColumn } from "./ITechControlColumn";
import { ITechControlSchema } from "./ITechControlSchema";



export class ITechControlTable {
    
    public rowId: number;
    public dateInserted: number | null;
    public dateModified: number | null;
    public dateArchived: number | null;
    public status: number[];
    public guid: number[];
    public signature: number[];
    public iTechControlSchemaRowId: number | null;
    public name: string;
    public iTechControlDatabaseSchemaTypeRowId: number | null;
    public description: string;
    public icon: string;
    public iTechControlColumns: ITechControlColumn[];
    public iTechControlSchemaRow: ITechControlSchema;
}


































