
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { Expression } from "./Expression";
import { TermAction } from "./TermAction";



export class ITermCheckedSet {
    
    public excludedIds: number[];
    public expressions: Expression[];
    public search: string;
    public action: TermAction;
}


































