
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataSecurityObject } from "./ITechDataSecurityObject";
import { ITechWebLexicon } from "./ITechWebLexicon";



export class LexiconGroup {
    
    public gid: number;
    public iTechDataSecurityObject: ITechDataSecurityObject;
    public iTechDataRiskTypeRowId: number | null;
    public iTechDataRiskCategoryTypeRowId: number | null;
    public iTechDataScenarioTypeRowId: number | null;
    public name: string;
    public lexicons: ITechWebLexicon[];
}


































