
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { MsGraphChatMsgChannelIdentity } from "./MsGraphChatMsgChannelIdentity";
import { MsGraphChatMsgFrom } from "./MsGraphChatMsgFrom";
import { MsGraphChatMsgBody } from "./MsGraphChatMsgBody";
import { ChatMessageAttachment } from "./ChatMessageAttachment";
import { MsGraphChatMsgReaction } from "./MsGraphChatMsgReaction";



export class MsGraphGetChatMsgResponse {
    
    public odataContext: string;
    public id: string;
    public replyToId: string;
    public etag: string;
    public messageType: string;
    public createdDateTime: Date;
    public lastModifiedDateTime: Date;
    public lastEditedDateTime: any;
    public deletedDateTime: any;
    public subject: any;
    public summary: any;
    public chatId: string;
    public importance: string;
    public locale: string;
    public webUrl: any;
    public channelIdentity: MsGraphChatMsgChannelIdentity;
    public policyViolation: any;
    public eventDetail: any;
    public from: MsGraphChatMsgFrom;
    public body: MsGraphChatMsgBody;
    public attachments: ChatMessageAttachment[];
    public mentions: any[];
    public reactions: MsGraphChatMsgReaction[];
}


































