
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
import { MsGraphChatMsgUser } from "./MsGraphChatMsgUser";



export class MsGraphChatMsgFrom {
    
    public application: any;
    public device: any;
    public conversation: any;
    public user: MsGraphChatMsgUser;
}


































