
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { iTechDataWebTemplateEnum } from "./iTechDataWebTemplateEnum";
import { AdvancedFilterModel } from "./AdvancedFilterModel";



export class NewTemplateRequest {
    
    public tabId: string;
    public name: string;
    public type: iTechDataWebTemplateEnum;
    public appliedFilters: AdvancedFilterModel;
    public appliedTreeFilters: AdvancedFilterModel;
}


































