
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum NoteLinkType {
    case = 1,
    sim = 2,
    task = 3,
    auditSim = 4,
    auditData = 5,
    accident = 6,
    salesForce = 7,
    tab = 8,
    user = 9
}

































