
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class NoteModel {
    
    public rowId: number;
    public noteType: string;
    public title: string;
    public text: string;
    public dateModified: string;
    public createdBy: string;
    public iTechDataNoteParentRowId: number | null;
    public sendToSecurityIds: number[];
    public htmlNote: string;
}


































