
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { iTechControlSearchEnum } from "./iTechControlSearchEnum";



export class PageParams {
    
    public start: number;
    public count: number;
    public sortBy: string;
    public sortDirection: string;
    public search: string;
    public options: iTechControlSearchEnum[];
}


































