
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class RdhSummaryCaptured {
    
    public globalRowId: number | null;
    public globalName: string;
    public sourceDatabaseId: number | null;
    public sourceDatabaseName: string;
    public globalDatabaseId: number | null;
    public globalConnectionString: string;
    public count: number | null;
}


































