
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechDataTask } from "./ITechDataTask";
import { ITechDataUser } from "./ITechDataUser";
import { ITechDataRulePartType } from "./ITechDataRulePartType";



export class RuleTask {
    
    public rowId: number;
    public name: string;
    public json: string;
    public filterJSON: string;
    public ruleType: string;
    public filterCount: number;
    public disabled: boolean | null;
    public iTechDataRuleTypeRowId: number | null;
    public workflow: ITechDataTask[];
    public users: ITechDataUser[];
    public parts: ITechDataRulePartType[];
}


































