
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class Services {
    
    public actionCount: number | null;
    public errorCount: number | null;
    public host: string;
    public database: string;
    public connection: string;
    public serviceType: string;
    public service: string;
    public comments: string;
    public startOnLoad: string;
    public resetHolder: string;
    public restartType: string;
    public restartMinInterval: number | null;
    public restartInterval: number | null;
    public maxRunTime: number | null;
}


































