
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { iTechControlFileEnum } from "./iTechControlFileEnum";
import { iTechControlSimToFsiEnum } from "./iTechControlSimToFsiEnum";
import { IFilePreview } from "./IFilePreview";



export class SimData implements IFilePreview {
    
    public iTechSimToFsiRowId: number;
    public iTechSimRowId: number | null;
    public iTechControlFileType: iTechControlFileEnum;
    public iTechControlSimToFsiType: iTechControlSimToFsiEnum;
    public obDateInserted: Date;
    public name: string;
    public summary: string;
    public iTechSimToFsiParentRowId: number | null;
    public fileTypeAbb: string;
    public fileTypeDescription: string;
    public fsiGuid: number[];
    public rowId: number;
    public previewType: string;
}


































