
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { IFilePreview } from "./IFilePreview";



export class SimVersion implements IFilePreview {
    
    public iTechSimVersionRowId: number;
    public iTechSimRowId: number | null;
    public version: number | null;
    public dateInserted: Date;
    public obDateCreated: Date;
    public fileTypeAbb: string;
    public fileTypeDescription: string;
    public summary: string;
    public name: string;
    public fsiGuid: number[];
    public rowId: number;
    public previewType: string;
}


































