
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
import { StockCandleStick } from "./StockCandleStick";







export class StockData {
    
    public data: StockCandleStick[];
    public events: GraphEvent[];
    public comms: GraphEvent[];
    public oms: GraphEvent[];
}
export class StockDataBoost {
    
    public data: number[][];
    public events: GraphEvent[];
    public comms: GraphEvent[];
    public oms: GraphEvent[];
}
export class GraphEvent {
    
    public date: Date;
    public dateTicks: number | null;
    public title: string;
    public url: string;
    public description: string;
    public type: GraphEventType;
    public y: number | null;
    public subType: number;
    public rowId: number;
}

export enum GraphEventType {
    alert = 0,
    order = 1,
    news = 2,
    communication = 3
}

































