
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

import { ITechWebRule } from "./ITechWebRule";

import { IRowId } from "./IRowId";





import { ITechDataTask } from "./ITechDataTask";
import { ITechDataUser } from "./ITechDataUser";



export class SurveillanceRule extends ITechWebRule {
    
    public score: number | null;
    public index: number | null;
}
export class SurveillanceTask {
    
    public rowId: number;
    public name: string;
    public description: string;
    public comments: string;
    public threshold: number | null;
    public isOrdered: boolean | null;
    public disabled: boolean | null;
    public filterJSON: string;
    public filterCount: number;
    public iTechDataRiskTypeRowId: number | null;
    public iTechDataRiskCategoryTypeRowId: number | null;
    public iTechDataScenarioTypeRowId: number | null;
    public rules: SurveillanceRule[];
    public workflow: ITechDataTask[];
    public users: ITechDataUser[];
}


































