
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class AssureReport {
    
    public title: string;
    public date: Date;
    public summary: Summary;
    public detail: Detail;
}
export class Summary {
    
    public userComplianceStatus: TableModel;
    public notCompliantReason: TableModel;
    public lineTestStatus: TableModel;
    public status: TableModel;
}
export class Detail {
    
    public sourceSystem: TableModel;
    public failedLineTest: TableModel;
    public recorder: TableModel;
    public office: TableModel;
    public qualityOutcome: TableModel;
    public qualitySource: TableModel;
    public qualityRecorder: TableModel;
    public qualityOffice: TableModel;
    public recordingsAnalysis: TableModel;
    public mixDetailTestCode: TableModel;
    public mixDetailLineTestOutcome: TableModel;
}
export class TableModel {
    
    public header: string[];
    public data: any[][];
}


































