
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class TeamsConversation {
    
    public teamsIMs: TeamsIM[];
    public teamsMembers: TeamsMembers[];
}
export class TeamsIM {
    
    public messageType: string;
    public subject: string;
    public createDateTime: string;
    public importance: string;
    public chatId: string;
    public id: string;
    public locale: string;
    public body: TeamsBody;
    public from: TeamsFrom;
}
export class TeamsFrom {
    
    public user: TeamsUser;
}
export class TeamsUser {
    
    public id: string;
    public displayName: string;
}
export class TeamsBody {
    
    public contentType: string;
    public content: string;
}
export class TeamsMembers {
    
    public value: TeamsMember[];
}
export class TeamsMember {
    
    public displayName: string;
    public userId: string;
    public email: string;
    public tenantId: string;
}


































