
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



export enum TimePeriodEnum {
    all = 0,
    lastFiveMinutes = 1,
    lastHour = 2,
    yesterday = 3,
    lastWeek = 4,
    lastMonth = 5,
    lastYear = 6
}

































