
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class TotalsSelection {
    
    public companies: string[];
    public dayOfWeekCnt: number[];
    public fileTypes: FileType[];
}
export class FileType {
    
    public fileTypeAbb: string;
    public description: string;
}


































