
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************




export class VendorSim {
    
    public dateInsertedString: string;
    public documentGuid: string;
    public duration: number | null;
    public fileSize: number | null;
    public fileTypeAbb: string;
    public fromAddress: string;
    public id: number;
    public name: string;
    public obDateCreatedString: string;
    public summary: string;
    public toAddress: string;
}


































