//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH A TYPESCRIPT CODE GENERATION TOOL AND ANY MODIFICATIONS MADE HERE WILL BE LOST.
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

export class ITechResultRow {
  public iTechSimRowId: number;
  public rowId: number | null;
  public auditType: AuditType | null;
}

export enum AuditType {
  sim = 0,
  data = 1,
}
