export const WIZARD_STATE = {
  CHOOSE_COMPONENT: "CHOOSE_COMPONENT",
  CHOOSE_RESULTSET: "CHOOSE_RESULTSET",
  CONFIGURE_GRID: "CONFIGURE_GRID",
  CONFIGURE_TREE: "CONFIGURE_TREE",
  CONFIGURE_DATA_SOURCE: "CONFIGURE_DATA_SOURCE",
  CONFIGURE_COLUMNS: "CONFIGURE_COLUMNS",
  CONFIGURE_CHART: "CONFIGURE_CHART",
  CONFIGURE_COUNTER: "CONFIGURE_COUNTER",
  CONFIGURE_NOTES: "CONFIGURE_NOTES",
  CONFIGURE_HIERARCHY: "CONFIGURE_HIERARCHY",
};
