export enum ComponentType {
  Wizard = "Wizard",
  VirtualTable = "VirtualTable",
  TreeFilter = "Tree Filter",
  AdvancedFilter = "Advanced Filter",
  Preview = "Preview",
  Properties = "Properties",
  Counter = "Counter",
  ChangeComponent = "ChangeComponent",
  TabNotes = "TabNotes",
  NoteList = "NoteList",
  CaseNotes = "Case Notes",
  ObjectAudit = "Audit",
  Versions = "Versions",
  CaseProperties = "Case Properties",
  IDVerification = "User Identity",
  Actions = "Actions",
  CaseUsers = "Case Users",
  Hierarchy = "Hierarchy",
  CollectionTotalGrid = "Collection Total Table",
  AssureReport = "Assure Report",
} // Charts in chartwizard also component types..
